file(MAKE_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/exefs)

add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/sys/tools/deploy.py ${CMAKE_CURRENT_BINARY_DIR} ${PROJECT_NAME} ${TITLE_ID} ${MODULE_BINARY} ${TARGET_IS_STATIC}
)
