#pragma once
#include "game/System/GameDataFunction.h"

#include <string>
#include <vector>

namespace StageWarper {

extern bool IsOpen;

// Sets the stage list (e.g., StageLoader::getAllStageNames)
void SetStageList(const std::vector<std::string>& stages);
// TODO: make it be not hardcoded
static const char* g_stages[] = {"CapWorldHomeStage",
                                 "CapWorldTowerStage",
                                 "FrogSearchExStage",
                                 "PoisonWaveExStage",
                                 "PushBlockExStage",
                                 "RollingExStage",
                                 "WaterfallWorldHomeStage",
                                 "TrexPoppunExStage",
                                 "Lift2DExStage",
                                 "WanwanClashExStage",
                                 "CapAppearExStage",
                                 "WindBlowExStage",
                                 "SandWorldHomeStage",
                                 "SandWorldShopStage",
                                 "SandWorldSlotStage",
                                 "SandWorldVibrationStage",
                                 "SandWorldSecretStage",
                                 "SandWorldMeganeExStage",
                                 "SandWorldKillerExStage",
                                 "SandWorldPressExStage",
                                 "SandWorldSphinxExStage",
                                 "SandWorldCostumeStage",
                                 "SandWorldPyramid000Stage",
                                 "SandWorldPyramid001Stage",
                                 "SandWorldUnderground000Stage",
                                 "SandWorldUnderground001Stage",
                                 "SandWorldRotateExStage",
                                 "MeganeLiftExStage",
                                 "RocketFlowerExStage",
                                 "WaterTubeExStage",
                                 "LakeWorldHomeStage",
                                 "LakeWorldShopStage",
                                 "FastenerExStage",
                                 "TrampolineWallCatchExStage",
                                 "GotogotonExStage",
                                 "FrogPoisonExStage",
                                 "ForestWorldHomeStage",
                                 "ForestWorldWaterExStage",
                                 "ForestWorldTowerStage",
                                 "ForestWorldBossStage",
                                 "ForestWorldBonusStage",
                                 "ForestWorldCloudBonusExStage",
                                 "FogMountainExStage",
                                 "RailCollisionExStage",
                                 "ShootingElevatorExStage",
                                 "ForestWorldWoodsStage",
                                 "ForestWorldWoodsTreasureStage",
                                 "ForestWorldWoodsCostumeStage",
                                 "PackunPoisonExStage",
                                 "AnimalChaseExStage",
                                 "KillerRoadExStage",
                                 "CloudWorldHomeStage",
                                 "FukuwaraiKuriboStage",
                                 "Cube2DExStage",
                                 "ClashWorldHomeStage",
                                 "ClashWorldShopStage",
                                 "ImomuPoisonExStage",
                                 "JangoExStage",
                                 "CityWorldHomeStage",
                                 "CityWorldMainTowerStage",
                                 "CityWorldFactoryStage",
                                 "CityWorldShop01Stage",
                                 "CityWorldSandSlotStage",
                                 "CityPeopleRoadStage",
                                 "PoleGrabCeilExStage",
                                 "TrexBikeExStage",
                                 "PoleKillerExStage",
                                 "Note2D3DRoomExStage",
                                 "ShootingCityExStage",
                                 "CapRotatePackunExStage",
                                 "RadioControlExStage",
                                 "ElectricWireExStage",
                                 "Theater2DExStage",
                                 "DonsukeExStage",
                                 "SwingSteelExStage",
                                 "BikeSteelExStage",
                                 "SnowWorldHomeStage",
                                 "SnowWorldTownStage",
                                 "SnowWorldShopStage",
                                 "SnowWorldLobby000Stage",
                                 "SnowWorldLobby001Stage",
                                 "SnowWorldRaceTutorialStage",
                                 "SnowWorldRace000Stage",
                                 "SnowWorldRace001Stage",
                                 "SnowWorldCostumeStage",
                                 "SnowWorldCloudBonusExStage",
                                 "IceWalkerExStage",
                                 "IceWaterBlockExStage",
                                 "ByugoPuzzleExStage",
                                 "IceWaterDashExStage",
                                 "SnowWorldLobbyExStage",
                                 "SnowWorldRaceExStage",
                                 "SnowWorldRaceHardExStage",
                                 "KillerRailCollisionExStage",
                                 "SeaWorldHomeStage",
                                 "SeaWorldUtsuboCaveStage",
                                 "SeaWorldVibrationStage",
                                 "SeaWorldSecretStage",
                                 "SeaWorldCostumeStage",
                                 "SeaWorldSneakingManStage",
                                 "SenobiTowerExStage",
                                 "CloudExStage",
                                 "WaterValleyExStage",
                                 "ReflectBombExStage",
                                 "TogezoRotateExStage",
                                 "LavaWorldHomeStage",
                                 "LavaWorldUpDownExStage",
                                 "LavaBonus1Zone",
                                 "LavaWorldShopStage",
                                 "LavaWorldCostumeStage",
                                 "ForkExStage",
                                 "LavaWorldExcavationExStage",
                                 "LavaWorldClockExStage",
                                 "LavaWorldBubbleLaneExStage",
                                 "LavaWorldTreasureStage",
                                 "GabuzouClockExStage",
                                 "CapAppearLavaLiftExStage",
                                 "LavaWorldFenceLiftExStage",
                                 "BossRaidWorldHomeStage",
                                 "DotTowerExStage",
                                 "BullRunExStage",
                                 "SkyWorldHomeStage",
                                 "SkyWorldShopStage",
                                 "SkyWorldCostumeStage",
                                 "SkyWorldCloudBonusExStage",
                                 "SkyWorldTreasureStage",
                                 "JizoSwitchExStage",
                                 "TsukkunRotateExStage",
                                 "KaronWingTowerStage",
                                 "TsukkunClimbExStage",
                                 "MoonWorldHomeStage",
                                 "MoonWorldCaptureParadeStage",
                                 "MoonWorldWeddingRoomStage",
                                 "MoonWorldKoopa1Stage",
                                 "MoonWorldBasementStage",
                                 "MoonWorldWeddingRoom2Stage",
                                 "MoonWorldKoopa2Stage",
                                 "MoonWorldShopRoom",
                                 "MoonWorldSphinxRoom",
                                 "MoonAthleticExStage",
                                 "Galaxy2DExStage",
                                 "PeachWorldHomeStage",
                                 "PeachWorldShopStage",
                                 "PeachWorldCastleStage",
                                 "PeachWorldCostumeStage",
                                 "FukuwaraiMarioStage",
                                 "DotHardExStage",
                                 "YoshiCloudExStage",
                                 "PeachWorldPictureBossMagmaStage",
                                 "RevengeBossMagmaStage",
                                 "PeachWorldPictureGiantWanderBossStage",
                                 "RevengeGiantWanderBossStage",
                                 "PeachWorldPictureBossKnuckleStage",
                                 "RevengeBossKnuckleStage",
                                 "PeachWorldPictureBossForestStage",
                                 "RevengeForestBossStage",
                                 "PeachWorldPictureMofumofuStage",
                                 "RevengeMofumofuStage",
                                 "PeachWorldPictureBossRaidStage",
                                 "RevengeBossRaidStage",
                                 "Special1WorldHomeStage",
                                 "Special1WorldTowerStackerStage",
                                 "Special1WorldTowerBombTailStage",
                                 "Special1WorldTowerFireBlowerStage",
                                 "Special1WorldTowerCapThrowerStage",
                                 "KillerRoadNoCapExStage",
                                 "PackunPoisonNoCapExStage",
                                 "BikeSteelNoCapExStage",
                                 "ShootingCityYoshiExStage",
                                 "SenobiTowerYoshiExStage",
                                 "LavaWorldUpDownYoshiExStage",
                                 "Special2WorldHomeStage",
                                 "Special2WorldLavaStage",
                                 "Special2WorldCloudStage",
                                 "Special2WorldKoopaStage",
                                 "HomeShipInsideStage"};

// Shows the stage search window (optional UI entry point)
void ShowSearchWindow();

// Warp to a stage by name
void warpPlayer(const char* stageName);

}  // namespace StageWarper
