#pragma once

#include <heap/seadDisposer.h>

#include "game/Player/PlayerActorBase.h"
#include "game/Scene/StageScene.h"
#include "game/Sequence/HakoniwaSequence.h"
#include "game/Player/PlayerActorHakoniwa.h"
#include "imgui.h"
#include "sead/math/seadQuat.h"
#include "settings/SettingsMgr.h"

namespace btt {

class Menu {
    SEAD_SINGLETON_DISPOSER(Menu)

public:
    Menu() = default;
    bool mIsEnabledMenu = true;

    struct TpState {
        bool saved;
        sead::Vector3f pos = { 0, 0, 0 };
        sead::Quatf quat = { 0, 0, 0, 0 };
        char stageName[0x40] = {};
    };

    TpState tpStates[0x8];

    void draw();
    void setupStyle();
    void handleAlways();
    const char* getMoonRefreshText();

    bool noGetPlayer = false;
    u64 globalTimer = 0;

private:
    ImVec2 mWindowSize = ImVec2(500, 400);

    HakoniwaSequence* gameSeq;
    PlayerActorBase* player;
    StageScene* stageScene;
    PlayerActorHakoniwa* playerHak;
    GameDataHolder* holder;
    SettingsMgr* set;

    ImGuiID prevNavId = 0;
    u64 prevTime = 0;

    void drawInputDisabled();
    void drawMiscCat();
        constexpr static const char* MoonRefreshTexts[] {
            "SMOO+ Panel",
            "BTT",
            "Hi BTT",
            "I am Cool",
            "Super Mario Odyssey",
            "Entrance to Shiveria",
            "<blank>"
        };
    void drawTeleportCat();
    void drawHotkeysCat();
    bool isHotkey(int& key);
        constexpr static const char* Keys[] {
            "Disabled",
            "None",
            "L",
            "R",
            "ZL",
            "ZR",
            "L + R",
            "L + ZL",
            "L + ZR",
            "R + ZL",
            "R + ZR",
        };
        int killSceneKey = 0;
        int healMarioKey = 0;

    void drawInfoCat();
        int sliderValue = 2;
        char format[16];
        char textBuffer[64];

    int tpIndex = 0;
    void saveTeleport(TpState& state);
    void loadTeleport(TpState& state);


    //Animations Player
    bool isAnimHotkey(int key);
        constexpr static const char* Animation[] {
            "AreaWait64",
            "AreaWaitAloha",
            "AreaWaitBalance",
            "AreaWaitBeach",
            "AreaWaitCold",
            "AreaWaitDance01",
            "AreaWaitDance02",
            "AreaWaitDance03",
            "AreaWaitFight",
            "AreaWaitGetwarm",
            "AreaWaitGuitar",
            "AreaWaitHeatGround",
            "AreaWaitHot",
            "AreaWaitJog",
            "AreaWaitLookUp",
            "AreaWaitSayCheese",
            "AreaWaitScared",
            "AreaWaitSigh",
            "AreaWaitSitDown",
            "AreaWaitSleepy",
            "AreaWaitSmell",
            "AreaWaitStink",
            "AreaWaitStretch",
            "AreaWaitView",
            "AreaWaitWaterfall",
            "AreaWaitWonder",
            "ArrowShoot",
            "ArrowStart",
            "BallToss",
            "BallTossGround",
            "BattleWait",
            "BedSleep",
            "BedSleepStart",
            "BedSnooze",
            "BedSnoozeStart",
            "BikeRide",
            "Bind",
            "Brake",
            "BubbleJump",
            "BubbleStart",
            "BubbleWait",
            "CanoeDamage",
            "CanoeDamageEnd",
            "CanoePaddle",
            "CanoeTurnL",
            "CanoeTurnR",
            "CanoeWait",
            "Carry",
            "CarryFront",
            "CarryFrontStart",
            "CarryFrontThrow",
            "CarryUp",
            "CarryUpStart",
            "CarryUpThrow",
            "CatapultStart",
            "CatchCap",
            "CatchCapJump",
            "CatchCapJumpParts",
            "CatchCapJumpPartsReverse",
            "CatchCapParts",
            "CatchKoopaCap",
            "ClashWorldStandUp",
            "ClimbTreeHandStandWait",
            "Damage",
            "DamageLand",
            "Damage",
            "DamageSwim",
            "DamageSwimSurface",
            "DamageSwimSurfaceLand",
            "DamageWait",
            "Dash",
            "DashBrake",
            "DashFast",
            "DashTurn",
            "Dead",
            "Dead01",
            "Dead02",
            "Dead03",
            "Dead04",
            "DeadFall",
            "DeadFire",
            "DeadIce",
            "DeadFire",
            "DeadPoison",
            "DeadSand",
            "DeadWallow",
            "DeadWater",
            "DemoAppearFromHome",
            "DemoBattleEndGiantWanderBoss",
            "DemoBattleStartBossKnuckle",
            "DemoBattleStartBreeda",
            "DemoBattleStartBreedaFirst",
            "DemoBattleStartGolemClimb",
            "DemoBossRaidAttack",
            "DemoCrashHome",
            "DemoCrashHomeFall",
            "DemoEnding01",
            "DemoEnding02",
            "DemoEnding03",
            "DemoEnding04",
            "DemoEnterChurch",
            "DemoGetShine",
            "DemoGetShineCloseUp",
            "DemoGetShineEnd",
            "DemoGetShineGrandCloseUp",
            "DemoGetShineGrandCloseUpEnd",
            "DemoGetShineGrandEnd",
            "DemoGetShineGrandStart",
            "DemoGetShineLand",
            "DemoGetShinePaper",
            "DemoGetShineRock",
            "DemoGetShineScissors",
            "DemoGetShineStart",
            "DemoGetShineHackFirst",
            "DemoHackFirst",
            "DemoHackKoopa01",
            "DemoHackKoopa02",
            "DemoJangoCapSearch",
            "DemoJangoGetUp",
            "DemoJangoLookAround",
            "DemoJangoStolen",
            "DemoJangoStolenLoop",
            "DemoMeetCapNpcC01",
            "DemoMeetCapNpcC01TalkWait",
            "DemoMeetCapNpcC02",
            "DemoMeetCapNpcC02ATalkWait",
            "DemoMeetCapNpcC02BTalkWait",
            "DemoMeetCapNpcC03",
            "DemoMeetCapNpcC04TalkWait",
            "DemoMeetCapNpcC06TalkWait",
            "DemoMeetCapNpcC07TalkWait",
            "DemoMeetCapNpcC08TalkWait",
            "DemoMeetCapNpcC10A",
            "DemoMeetCapNpcC10ATalkWait",
            "DemoMeetCapNpcC10B",
            "DemoMeetCapNpcC10BTalkWait",
            "DemoOpening01",
            "DemoOpeningCap",
            "DemoOpeningDown",
            "DemoPayToHome",
            "DemoReset",
            "DemoReturnHome",
            "DemoSitDownTalk",
            "DemoSitDownWaitFirst",
            "DemoStartJango",
            "DemoStartJango2",
            "DemoStartUpHome",
            "DemoStartUpHomeSky",
            "DemoStartWaterfall",
            "DemoTakeOffKoopaForMoon",
            "DemoTalkCapManHeroAppear",
            "DemoTalkCapManHeroWalk",
            "DemoWarpEnd",
            "DemoWarpStart",
            "DemoWorldLavaScenario1End",
            "DemoWorldMoveBackward",
            "DemoWorldMoveBackward1",
            "DemoWorldMoveBackward2",
            "DemoWorldMoveBackward3",
            "DemoWorldMoveForward",
            "DemoWorldMoveForwardArrive",
            "DemoWorldMoveForwardNormal1",
            "DemoWorldMoveForwardNormal2",
            "DemoWorldMoveForwardNormal3",
            "DemoWorldMoveMoonBackward",
            "DemoWorldMoveMoonForward",
            "DemoWorldMoveMoonForwardFirst",
            "DemoWorldTakeoff",
            "DemoWorldTakeoffEast",
            "DemoWorldTakeoffForMoon",
            "DemoWorldTakeoffForMoonFirst",
            "DemoWorldTakeoffForMoonFirstTuxedo",
            "DemoWorldTakeoffWest",
            "DemoWorldWarpHole01",
            "DemoWorldWarpHole02",
            "DemoWorldWarpHole03",
            "Dive",
            "DiveInWater",
            "DokanIn",
            "DokanInHome",
            "DokanInUpsideDown",
            "DokanJump",
            "DokanOutUpsideDown",
            "DokanReady",
            "DokanSideIn",
            "DokanSideOut",
            "DoorIn",
            "DoorOut",
            "Fall",
            "Fire",
            "FireRun",
            "FireRunStart",
            "GetShine",
            "GetShineCity",
            "GetShineEmpty",
            "GetShineGrand",
            "GetShineSub",
            "GrabCeilJump",
            "GrabCeilStart",
            "GrabCeilSwing",
            "GrabCeilWait",
            "Hack",
            "HeadSliding",
            "HeadSlidingStart",
            "HipDrop",
            "HipDropLand",
            "HipDropReaction",
            "HipDropStart",
            "HomeCapManHeroAppear",
            "Jump",
            "Jump2",
            "Jump3",
            "JumpBack",
            "JumpBroad",
            "JumpBroad2",
            "JumpBroad3",
            "JumpBroad4",
            "JumpBroad5",
            "JumpBroad6",
            "JumpBroad7",
            "JumpBroad8",
            "JumpBroad9",
            "JumpCapCatchCommon",
            "JumpCapLeapFrog",
            "JumpDashFast",
            "JumpEndHack",
            "JumpFlap",
            "JumpHipDrop",
            "JumpInterp",
            "JumpNpcTranple",
            "JumpObjectReaction",
            "JumpReverse",
            "JumpReverseInterp",
            "JumpTurn",
            "Kick",
            "KoopaCapPunchFinishL",
            "KoopaCapPunchFinishLStart",
            "KoopaCapPunchFinishR",
            "KoopaCapPunchFinishRStart",
            "KoopaCapPunchL",
            "KoopaCapPunchLStart",
            "KoopaCapPunchR",
            "KoopaCapPunchRStart",
            "KoopaDemoBattleStartChurchFirstLv2",
            "KoopaDemoBattleStartChurchLv2",
            "KoopaDemoBattleStartChurchSecondLv2",
            "KoopaDemoBattleStartLv1",
            "KoopaDemoBattleStartLv2",
            "KoopaDemoBattleStartTalkBlendLv1",
            "KoopaDemoClashBasement",
            "Land",
            "LandDownFall",
            "LandJump3",
            "LandRolling",
            "LandStiffen",
            "LandTurn",
            "MainScenarioCameraWait",
            "MofumofuDemoOpening1",
            "MofumofuDemoOpening2",
            "MotorcycleRideC",
            "MotorcycleRideClashC",
            "MotorcycleRideClashL",
            "MotorcycleRideClashR",
            "MotorcycleRideJumpC",
            "MotorcycleRideL",
            "MotorcycleRideR",
            "MotorcycleRideL",
            "MotorcycleRideLandC",
            "MotorcycleRideLandL",
            "MotorcycleRideR",
            "MotorcycleRideRunStartC",
            "MotorcycleRideRunStartL",
            "MotorcycleRideRunStartR",
            "MotorcycleRideStart",
            "MotorcycleRideStartL",
            "MotorcycleRideStartR",
            "MotorcycleWait",
            "OpeningStandUp",
            "PauseMenu2Player",
            "PauseMenuContinue",
            "PauseMenuContinueEnd",
            "PauseMenuData",
            "PauseMenuHelp",
            "PauseMenuNewGame",
            "PauseMenuSave",
            "PauseMenuStart",
            "PauseMenuWait",
            "PoleCatch",
            "PoleClimb",
            "PoleFall",
            "PoleHandStandEnd",
            "PoleHandStandJump",
            "PoleHandStandStart",
            "PoleHandStandTurn",
            "PoleHandStandWait",
            "PoleTurn",
            "PoleWait",
            "Punch",
            "Push",
            "RabbitGet",
            "RaceManHack",
            "RaceManHackEnd",
            "RaceManHackStart",
            "RaceManHackJumpEnd",
            "RaceManHackJumpStart",
            "RaceManResultLose",
            "RaceManResultWin",
            "RaceResultLose",
            "RaceResultWin",
            "ReactionCapOn",
            "Rolling",
            "RollingEnd",
            "RollingEndBackUp",
            "RollingJump",
            "RollingLand",
            "RollingStandUp",
            "RollingStart",
            "RoswellPut",
            "RoswellRun",
            "RoswellThrow",
            "Run",
            "RunMoon",
            "RunStart",
            "SandWaitNormal",
            "SandWaitStrong",
            "SandWalkNormal",
            "SandWalkStrong",
            "SitDown",
            "SitDownEnd",
            "SitDownLand",
            "SitDownSleep",
            "SitDownSleepEnd",
            "SitDownSleepStart",
            "SitDownStart",
            "Sleep",
            "SleepStart",
            "Slide",
            "SlopeSlide",
            "SlopeSlideBack",
            "Snooze",
            "SnoozeStart",
            "SphinxRideClash",
            "SphinxRideFall",
            "SphinxRideGetOn",
            "SphinxRideJump",
            "SphinxRideJumpStart",
            "SphinxRideOn",
            "SphinxRideRide",
            "SphinxRideRideOn",
            "SphinxRideRideStartL",
            "SphinxRideRideStartR",
            "SphinxRideRunSlow",
            "SphinxRideStop",
            "SphinxRideStopStart",
            "SpinCap",
            "SpinCapAirStart",
            "SpinCapAirStartCapCatch",
            "SpinCapAirStartDoubleDown",
            "SpinCapAirStartDoubleLeft",
            "SpinCapAirStartDoubleRight",
            "SpinCapAirStartDoubleUp",
            "SpinCapAirStartLeft",
            "SpinCapStartLong",
            "SpinCapStartRight",
            "SpinCapEnd",
            "SpinCapJumpStart",
            "SpinCapStart",
            "SpinCapStart2Left",
            "SpinCapStart2Right",
            "SpinCapStart3Left",
            "SpinCapStart3Right",
            "SpinCapStartCapCatch",
            "SpinCapStartDoubleDown",
            "SpinCapStartDoubleLeft",
            "SpinCapStartDoubleRight",
            "SpinCapStartDoubleUp",
            "SpinCapStartLeft",
            "SpinCapStartLong",
            "SpinCapStartRight",
            "SpinCapStartRolling",
            "SpinCapWait",
            "SpinGroundL",
            "SpinGroundR",
            "SpinJump",
            "SpinJumpDownFall",
            "SpinJumpDownFallL",
            "SpinJumpDownFallR",
            "SpinJumpL",
            "SpinJumpLoop",
            "SpinJumpR",
            "SpinJumpStart",
            "SpinSeperate",
            "SpinSeperateSwim",
            "SquatEnd",
            "SquatLand",
            "SquatStart",
            "SquatWait",
            "SquatWalk",
            "StabStart",
            "StabUndarWait",
            "StabUnderStart",
            "StabWait",
            "StabWallWait",
            "SwimDieOver",
            "SwimDive",
            "SwimFallIn",
            "SwimHeadSliding",
            "SwimHeadSlidingEnd",
            "SwimHeadSlidingIn",
            "SwimHeadSlidingStart",
            "SwimHipDrop",
            "SwimHipDropLand",
            "SwimHipDropStart",
            "SwimJumpHipDrop",
            "SwimLand",
            "SwimSpinCapStart",
            "SwimSpinCapStartDoubleDown",
            "SwimSpinCapStartDoubleLeft",
            "SwimSpinCapStartDoubleRight",
            "SwimSpinCapStartDoubleUp",
            "SwimSpinCapStartLeft",
            "SwimSpinCapStartRight",
            "SwimSquat",
            "SwimSquatWalk",
            "SwimStand",
            "SwimStandMove",
            "SwimStandSurface",
            "SwimStandWait",
            "SwimSurface",
            "SwimTalkWait",
            "SwimTrample",
            "SwimTrampoline",
            "SwimWait",
            "SwimWalk",
            "TalkEnd",
            "TalkTurn",
            "TalkTurnL90",
            "TalkTurnR90",
            "TalkWait",
            "TestDemoDiverA",
            "TestDemoDiverB",
            "TestDemoE3001",
            "TestRunBack",
            "TestRunFront",
            "TestRunLeft",
            "TestRunRight",
            "TestRunWait",
            "ThrowCap",
            "ThrowCapJump",
            "ThrowCapJumpParts",
            "ThrowCapParts",
            "TouchJump",
            "TouchJumpLong",
            "TouchJumpLongSign",
            "TractorBubbleEmd",
            "TractorBubbleEnd",
            "TractorBubbleStart",
            "TractorBubbleWait",
            "TreeClimb",
            "TreeFall",
            "Turn",
            "TurnPoint",
            "TurnStep",
            "Wait",
            "WaitCold",
            "WaitDemo",
            "WaitDigPoint",
            "WaitHot",
            "WaitRelax",
            "WaitRelaxStart",
            "WaitVeryCold",
            "Walk",
            "WalkDemo",
            "WalkSoft",
            "WallCatch",
            "WallCatchEnd",
            "WallCatchEndFast",
            "WallCatchEndJump",
            "WallCatchMoveL",
            "WallCatchMoveR",
            "WallCatchStart",
            "WallJump",
            "WallKeep",
            "WallKeepReverse",
            "WallLand",
            "WallSlideL",
            "WallSlideR",
            "WarpIn",
            "WarpOut",
            "WarpWait",
            "WarpOut",
            "WarpWait",
            "WaterRoadMove",
            "WearEnd",
            "WhipAttackEnd",
            "WhipAttackStart",
            "WhipAttackWait",
            "WhipWait",
            "WorldWarpBind",
            "WorldWarpBindStart",
            "WorldWarpIn",
            "WorldWarpOut",

        };
};
} // namespace btt
