#pragma once

namespace MessageMasterList {
struct MessageData {
    const char* label;
    const char* text;
    const char* stage;
    const char* objId;
};

struct AchievementMessageData {
    const char* label;
    const char* text;
};

inline constexpr MessageData shineList[775] = {
    {"ScenarioName_obj81", "Gap in the Ocean Trench", "SeaWorldSphinxQuizZone", "obj81"},
    {"ScenarioName_obj11", "Ocean Quiz: Good!", "SeaWorldSphinxQuizZone", "obj11"},
    {"ScenarioName_obj106", "The Tall Rock Shelf in the Deep Ocean", "SeaWorldSphinxQuizZone", "obj106"},
    {"ScenarioName_obj299", "Flying Far Away from Gusty Bridges", "WindBlowExStage", "obj299"},
    {"ScenarioName_obj167", "Across the Gusty Bridges", "WindBlowExStage", "obj167"},
    {"ScenarioName_obj5904", "Blowup at Mount Volbono: Rematch", "RevengeBossMagmaStage", "obj5904"},
    {"ScenarioName_obj226", "Extremely Hot Bath", "JangoExStage", "obj226"},
    {"ScenarioName_obj211", "Chasing Klepto", "JangoExStage", "obj211"},
    {"ScenarioName_obj122", "The Mummy Army's Curse", "BullRunExStage", "obj122"},
    {"ScenarioName_obj120", "Charging Through an Army", "BullRunExStage", "obj120"},
    {"ScenarioName_obj116", "Picture Match: Basically Mario", "FukuwaraiMarioStage", "obj116"},
    {"ScenarioName_obj117", "Picture Match: A Stellar Mario!", "FukuwaraiMarioStage", "obj117"},
    {"ScenarioName_obj35", "Courtyard Chest Trap", "PeachWorldCostumeStage", "obj35"},
    {"ScenarioName_obj13", "Totally Classic!", "PeachWorldCostumeStage", "obj13"},
    {"ScenarioName_obj15", "A Rumble from the Sandy Floor", "SandWorldVibrationStage", "obj15"},
    {"ScenarioName_obj918", "The Ice Wall Barrier", "SnowWorldTownStage", "obj918"},
    {"ScenarioName_obj987", "The Shiverian Treasure Chest", "SnowWorldTownStage", "obj987"},
    {"ScenarioName_obj1183", "Entrance to Shiveria", "SnowWorldTownStage", "obj1183"},
    {"ScenarioName_obj1185", "Shining in the Snow in Town", "SnowWorldTownStage", "obj1185"},
    {"ScenarioName_obj1187", "Found with Snow Kingdom Art", "SnowWorldTownStage", "obj1187"},
    {"ScenarioName_obj531", "The Icicle Barrier", "SnowWorldTownStage", "obj531"},
    {"ScenarioName_obj1134", "I'm Not Cold!", "SnowWorldTownStage", "obj1134"},
    {"ScenarioName_obj532", "The Gusty Barrier", "SnowWorldTownStage", "obj532"},
    {"ScenarioName_obj536", "The Snowy Mountain Barrier", "SnowWorldTownStage", "obj536"},
    {"ScenarioName_obj1101", "Peach in the Snow Kingdom", "SnowWorldTownStage", "obj1101"},
    {"ScenarioName_obj109", "Luncheon Kingdom Timer Challenge 2", "LavaWorldTimerAthletic001Zone", "obj109"},
    {"ScenarioName_obj100", "Luncheon Kingdom Timer Challenge 1", "LavaWorldTimerAthletic000Zone", "obj100"},
    {"ScenarioName_obj768", "Peach in the Lake Kingdom", "LakeWorldHomeStage", "obj768"},
    {"ScenarioName_obj848", "Lake Kingdom Regular Cup", "LakeWorldHomeStage", "obj848"},
    {"ScenarioName_obj783", "Bird Traveling Over the Lake", "LakeWorldHomeStage", "obj783"},
    {"ScenarioName_obj974", "Taxi Flying Through Lake Lamode", "LakeWorldHomeStage", "obj974"},
    {"ScenarioName_obj976", "Found with Lake Kingdom Art", "LakeWorldHomeStage", "obj976"},
    {"ScenarioName_obj326", "Broodals Over the Lake", "LakeWorldHomeStage", "obj326"},
    {"ScenarioName_obj918", "Love by the Lake", "LakeWorldHomeStage", "obj918"},
    {"ScenarioName_obj551", "Behind the Floodgate", "LakeWorldHomeStage", "obj551"},
    {"ScenarioName_obj396", "Taking Notes: Dive and Swim", "LakeWorldHomeStage", "obj396"},
    {"ScenarioName_obj859", "Lake Kingdom Master Cup", "LakeWorldHomeStage", "obj859"},
    {"ScenarioName_obj715", "On the Lakeshore", "LakeWorldHomeStage", "obj715"},
    {"ScenarioName_obj524", "Treasure in the Spiky Waterway", "LakeWorldHomeStage", "obj524"},
    {"ScenarioName_obj81", "Dashing Over Cold Water!", "IceWaterDashExStage", "obj81"},
    {"ScenarioName_obj262", "Dashing Above and Beyond!", "IceWaterDashExStage", "obj262"},
    {"ScenarioName_obj26", "Yoshi's Magma Swamp", "LavaWorldUpDownYoshiExStage", "obj26"},
    {"ScenarioName_obj27", "Fruit Feast in the Magma Swamp!", "LavaWorldUpDownYoshiExStage", "obj27"},
    {"ScenarioName_obj465", "The Spinning Maze: Search!", "TogezoRotateExStage", "obj465"},
    {"ScenarioName_obj958", "The Spinning Maze: Open!", "TogezoRotateExStage", "obj958"},
    {"ScenarioName_obj360", "Powering Up the Station", "CityWorldFactoryStage", "obj360"},
    {"ScenarioName_obj517", "Powering Up the Power Plant", "CityWorldFactoryStage", "obj517"},
    {"ScenarioName_obj2902", "Running the Flower Road", "KillerRailCollisionExStage", "obj2902"},
    {"ScenarioName_obj4422", "Looking Back on the Flower Road", "KillerRailCollisionExStage", "obj4422"},
    {"ScenarioName_obj400", "Glass Palace Treasure Chest", "SeaWorldUnderGlassZone", "obj400"},
    {"ScenarioName_obj345", "Lighthouse Leaper", "SeaWorldUnderGlassZone", "obj345"},
    {"ScenarioName_obj384", "Caught Hopping at Glass Palace!", "SeaWorldUnderGlassZone", "obj384"},
    {"ScenarioName_obj992", "Herding Sheep at Peach's Castle", "PeachWorldHomeStage", "obj992"},
    {"ScenarioName_obj1439", "Found at Peach's Castle! Good Dog!", "PeachWorldHomeStage", "obj1439"},
    {"ScenarioName_obj794", "Love at Peach's Castle", "PeachWorldHomeStage", "obj794"},
    {"ScenarioName_obj2364", "Perched on the Castle Roof", "PeachWorldHomeStage", "obj2364"},
    {"ScenarioName_obj281", "Secret Path to Peach's Castle!", "PeachWorldHomeStage", "obj281"},
    {"ScenarioName_obj1762", "Toad Defender", "PeachWorldHomeStage", "obj1762"},
    {"ScenarioName_obj2209", "Taking Notes: Around the Well", "PeachWorldHomeStage", "obj2209"},
    {"ScenarioName_obj1566", "Grow a Flower Garden", "PeachWorldHomeStage", "obj1566"},
    {"ScenarioName_obj1719", "Hat-and-Seek: Mushroom Kingdom", "PeachWorldHomeStage", "obj1719"},
    {"ScenarioName_obj1678", "Mushroom Kingdom Regular Cup", "PeachWorldHomeStage", "obj1678"},
    {"ScenarioName_obj1679", "Mushroom Kingdom Master Cup", "PeachWorldHomeStage", "obj1679"},
    {"ScenarioName_obj1473", "Gobbling Fruit with Yoshi", "PeachWorldHomeStage", "obj1473"},
    {"ScenarioName_obj1732", "Mushroom Kingdom Timer Challenge", "PeachWorldHomeStage", "obj1732"},
    {"ScenarioName_obj1495", "Yoshi's Second Helping!", "PeachWorldHomeStage", "obj1495"},
    {"ScenarioName_obj1497", "Yoshi's All Filled Up!", "PeachWorldHomeStage", "obj1497"},
    {"ScenarioName_obj734", "A Tourist in the Mushroom Kingdom!", "PeachWorldHomeStage", "obj734"},
    {"ScenarioName_obj1295", "Caught Hopping at Peach's Castle!", "PeachWorldHomeStage", "obj1295"},
    {"ScenarioName_obj2102", "Pops Out of the Tail", "PeachWorldHomeStage", "obj2102"},
    {"ScenarioName_obj1554", "Jammin' in the Mushroom Kingdom", "PeachWorldHomeStage", "obj1554"},
    {"ScenarioName_obj1507", "Princess Peach, Home Again!", "PeachWorldHomeStage", "obj1507"},
    {"ScenarioName_obj756", "Forever Onward, Captain Toad!", "PeachWorldHomeStage", "obj756"},
    {"ScenarioName_obj1100", "Gardening for Toad: Garden Seed", "PeachWorldHomeStage", "obj1100"},
    {"ScenarioName_obj1101", "Gardening for Toad: Field Seed", "PeachWorldHomeStage", "obj1101"},
    {"ScenarioName_obj1102", "Gardening for Toad: Lake Seed", "PeachWorldHomeStage", "obj1102"},
    {"ScenarioName_obj1103", "Gardening for Toad: Pasture Seed", "PeachWorldHomeStage", "obj1103"},
    {"ScenarioName_obj3726", "Big Jump: Escape!", "TrexBikeExStage", "obj3726"},
    {"ScenarioName_obj3656", "Motor Scooter: Escape!", "TrexBikeExStage", "obj3656"},
    {"ScenarioName_obj238", "What the Waves Left Behind", "SeaWorldLongReefZone", "obj238"},
    {"ScenarioName_obj361", "Found with Moon Kingdom Art", "MoonWorldWeddingRoomZone", "obj361"},
    {"ScenarioName_obj260", "Doctor in the House", "MoonWorldWeddingRoomZone", "obj260"},
    {"ScenarioName_obj11", "Walking on Clouds", "ForestWorldCloudBonusExStage", "obj11"},
    {"ScenarioName_obj1556", "Above the Clouds", "ForestWorldCloudBonusExStage", "obj1556"},
    {"ScenarioName_obj1052", "Moon Shards on the Moon", "MoonWorldHomeStage", "obj1052"},
    {"ScenarioName_obj937", "The Tip of a White Spire", "MoonWorldHomeStage", "obj937"},
    {"ScenarioName_obj1041", "Found on the Moon, Good Dog!", "MoonWorldHomeStage", "obj1041"},
    {"ScenarioName_obj877", "Moon Quiz: Amazing!", "MoonWorldHomeStage", "obj877"},
    {"ScenarioName_obj1391", "Thanks, Captain Toad!", "MoonWorldHomeStage", "obj1391"},
    {"ScenarioName_obj1199", "Hidden on the Side of the Cliff", "MoonWorldHomeStage", "obj1199"},
    {"ScenarioName_obj1399", "Mysterious Flying Object", "MoonWorldHomeStage", "obj1399"},
    {"ScenarioName_obj1039", "Walking on the Moon!", "MoonWorldHomeStage", "obj1039"},
    {"ScenarioName_obj997", "Peach in the Moon Kingdom", "MoonWorldHomeStage", "obj997"},
    {"ScenarioName_obj217", "Rolling Rock on the Moon", "MoonWorldHomeStage", "obj217"},
    {"ScenarioName_obj155", "Cliffside Treasure Chest", "MoonWorldHomeStage", "obj155"},
    {"ScenarioName_obj1216", "Jumping High as a Frog", "MoonWorldHomeStage", "obj1216"},
    {"ScenarioName_obj753", "Moon Kingdom Timer Challenge 1", "MoonWorldHomeStage", "obj753"},
    {"ScenarioName_obj1280", "Moon Kingdom Master Cup", "MoonWorldHomeStage", "obj1280"},
    {"ScenarioName_obj953", "Caught Hopping on the Moon!", "MoonWorldHomeStage", "obj953"},
    {"ScenarioName_obj1062", "Sneaking Around in the Crater", "MoonWorldHomeStage", "obj1062"},
    {"ScenarioName_obj944", "A Tourist in the Moon Kingdom!", "MoonWorldHomeStage", "obj944"},
    {"ScenarioName_obj1078", "Walking on the Moon: Again!", "MoonWorldHomeStage", "obj1078"},
    {"ScenarioName_obj1125", "Moon Kingdom Timer Challenge 2", "MoonWorldHomeStage", "obj1125"},
    {"ScenarioName_obj263", "Taking Notes: On the Moon's Surface", "MoonWorldHomeStage", "obj263"},
    {"ScenarioName_obj1064", "Moon Kingdom Regular Cup", "MoonWorldHomeStage", "obj1064"},
    {"ScenarioName_obj461", "Shining Above the Moon", "MoonWorldHomeStage", "obj461"},
    {"ScenarioName_obj54", "Inside the Rising Stone Pillar", "ClashWorldHomeStage", "obj54"},
    {"ScenarioName_obj595", "A Butterfly's Treasure", "ClashWorldHomeStage", "obj595"},
    {"ScenarioName_obj142", "Cave Gardening", "ClashWorldHomeStage", "obj142"},
    {"ScenarioName_obj2599", "Caught Hopping in the Jungle!", "ClashWorldHomeStage", "obj2599"},
    {"ScenarioName_obj2833", "Lost Kingdom Timer Challenge", "ClashWorldHomeStage", "obj2833"},
    {"ScenarioName_obj615", "Jump Down to the Top of a Tree", "ClashWorldHomeStage", "obj615"},
    {"ScenarioName_obj3283", "Twist 'n' Turn-Up Treasure", "ClashWorldHomeStage", "obj3283"},
    {"ScenarioName_obj616", "Line It Up, Blow It Up", "ClashWorldHomeStage", "obj616"},
    {"ScenarioName_obj3284", "Taxi Flying Through Forgotten Isle", "ClashWorldHomeStage", "obj3284"},
    {"ScenarioName_obj492", "On the Mountain Road", "ClashWorldHomeStage", "obj492"},
    {"ScenarioName_obj570", "Avoiding Fuzzies Inside the Wall", "ClashWorldHomeStage", "obj570"},
    {"ScenarioName_obj609", "The Shining Fruit", "ClashWorldHomeStage", "obj609"},
    {"ScenarioName_obj575", "Soaring Over Forgotten Isle!", "ClashWorldHomeStage", "obj575"},
    {"ScenarioName_obj2560", "Taking Notes: Stretch and Shrink", "ClashWorldHomeStage", "obj2560"},
    {"ScenarioName_obj39", "Inside the Stone Cage", "ClashWorldHomeStage", "obj39"},
    {"ScenarioName_obj83", "Get Some Rest, Captain Toad", "ClashWorldHomeStage", "obj83"},
    {"ScenarioName_obj564", "Below the Cliff's Edge", "ClashWorldHomeStage", "obj564"},
    {"ScenarioName_obj2862", "Lost Kingdom Master Cup", "ClashWorldHomeStage", "obj2862"},
    {"ScenarioName_obj111", "On a Tree in the Swamp", "ClashWorldHomeStage", "obj111"},
    {"ScenarioName_obj70", "Moon Shards in the Jungle", "ClashWorldHomeStage", "obj70"},
    {"ScenarioName_obj71", "Atop a Propeller Pillar", "ClashWorldHomeStage", "obj71"},
    {"ScenarioName_obj2774", "Lost Kingdom Regular Cup", "ClashWorldHomeStage", "obj2774"},
    {"ScenarioName_obj850", "The Caged Gold", "ClashWorldHomeStage", "obj850"},
    {"ScenarioName_obj1001", "Enjoying the View of Forgotten Isle", "ClashWorldHomeStage", "obj1001"},
    {"ScenarioName_obj2620", "Peach in the Lost Kingdom", "ClashWorldHomeStage", "obj2620"},
    {"ScenarioName_obj1144", "A Propeller Pillar's Secret", "ClashWorldHomeStage", "obj1144"},
    {"ScenarioName_obj2981", "Wrecked Rock Block", "ClashWorldHomeStage", "obj2981"},
    {"ScenarioName_obj701", "Peeking Out from Under the Bridge", "ClashWorldHomeStage", "obj701"},
    {"ScenarioName_obj2921", "I Met a Tropical Wiggler!", "ClashWorldHomeStage", "obj2921"},
    {"ScenarioName_obj920", "Over the Fuzzies, Above the Swamp", "ClashWorldHomeStage", "obj920"},
    {"ScenarioName_obj1277", "Battle in Bubblaine: Rematch", "RevengeGiantWanderBossStage", "obj1277"},
    {"ScenarioName_obj131", "Stretch on the Side Path", "SenobiTowerExStage", "obj131"},
    {"ScenarioName_obj162", "Hurry and Stretch", "SenobiTowerExStage", "obj162"},
    {"ScenarioName_obj1264", "Behind the Big Wall", "SkyWorldHomeStage", "obj1264"},
    {"ScenarioName_obj1673", "Taking Notes: Between Spinies", "SkyWorldHomeStage", "obj1673"},
    {"ScenarioName_obj1921", "Infiltrate Bowser's Castle!", "SkyWorldHomeStage", "obj1921"},
    {"ScenarioName_obj2204", "Jizo All in a Row", "SkyWorldHomeStage", "obj2204"},
    {"ScenarioName_obj2826", "Bowser's Kingdom Master Cup", "SkyWorldHomeStage", "obj2826"},
    {"ScenarioName_obj1390", "Taking Notes: On the Wall", "SkyWorldHomeStage", "obj1390"},
    {"ScenarioName_obj2569", "Peach in Bowser's Kingdom", "SkyWorldHomeStage", "obj2569"},
    {"ScenarioName_obj1394", "Jumping from Flag to Flag", "SkyWorldHomeStage", "obj1394"},
    {"ScenarioName_obj1380", "Caught on the Iron Fence", "SkyWorldHomeStage", "obj1380"},
    {"ScenarioName_obj1395", "Inside a Block at the Gate", "SkyWorldHomeStage", "obj1395"},
    {"ScenarioName_obj1596", "Secret Path to Bowser's Castle!", "SkyWorldHomeStage", "obj1596"},
    {"ScenarioName_obj1387", "Third Courtyard Outskirts", "SkyWorldHomeStage", "obj1387"},
    {"ScenarioName_obj1388", "Invader in Bowser's Castle", "SkyWorldHomeStage", "obj1388"},
    {"ScenarioName_obj1389", "Behind the Tall Wall: Poke, Poke!", "SkyWorldHomeStage", "obj1389"},
    {"ScenarioName_obj2720", "Bowser's Kingdom Regular Cup", "SkyWorldHomeStage", "obj2720"},
    {"ScenarioName_obj836", "Exterminate the Ogres!", "SkyWorldHomeStage", "obj836"},
    {"ScenarioName_obj2043", "Underground Jizo", "SkyWorldHomeStage", "obj2043"},
    {"ScenarioName_obj3285", "Small Bird in Bowser's Castle", "SkyWorldHomeStage", "obj3285"},
    {"ScenarioName_obj1740", "Poking Your Nose in the Plaster Wall", "SkyWorldHomeStage", "obj1740"},
    {"ScenarioName_obj3316", "Caught on the Giant Horn", "SkyWorldHomeStage", "obj3316"},
    {"ScenarioName_obj1809", "Stack Up Above the Wall", "SkyWorldHomeStage", "obj1809"},
    {"ScenarioName_obj21", "Shopping in Honeylune Ridge", "MoonWorldShopRoom", "obj21"},
    {"ScenarioName_obj342", "Across the Mysterious Clouds", "CapAppearExStage", "obj342"},
    {"ScenarioName_obj304", "Atop a Wall Among the Clouds", "CapAppearExStage", "obj304"},
    {"ScenarioName_obj116", "Picture Match: Basically a Goomba", "FukuwaraiKuriboStage", "obj116"},
    {"ScenarioName_obj117", "Picture Match: A Stellar Goomba!", "FukuwaraiKuriboStage", "obj117"},
    {"ScenarioName_obj880", "Jaxi Stunt Driving", "SandWorldSphinxExStage", "obj880"},
    {"ScenarioName_obj334", "Jaxi Driver", "SandWorldSphinxExStage", "obj334"},
    {"ScenarioName_obj509", "Rewiring the Neighborhood", "ElectricWireExStage", "obj509"},
    {"ScenarioName_obj764", "Off the Beaten Wire", "ElectricWireExStage", "obj764"},
    {"ScenarioName_obj606", "Rapid Ascent on Hot Spring Island", "SeaWorldLavaZone", "obj606"},
    {"ScenarioName_obj168", "The Hot Spring Seal", "SeaWorldLavaZone", "obj168"},
    {"ScenarioName_obj2512", "Sunken Treasure in the Cloud Sea", "CloudExStage", "obj2512"},
    {"ScenarioName_obj310", "Wading in the Cloud Sea", "CloudExStage", "obj310"},
    {"ScenarioName_obj92", "Wandering in the Fog", "FogMountainExStage", "obj92"},
    {"ScenarioName_obj249", "Nut Hidden in the Fog", "FogMountainExStage", "obj249"},
    {"ScenarioName_obj235", "Treasure in the Ice Wall", "SnowWorldGabuzouZone", "obj235"},
    {"ScenarioName_obj280", "Water Pooling in the Crevasse", "SnowWorldGabuzouZone", "obj280"},
    {"ScenarioName_obj206", "Ice-Dodging Goomba Stack", "SnowWorldIcicleZone", "obj206"},
    {"ScenarioName_obj412", "Stacked-Up Ice Climb", "SnowWorldIcicleZone", "obj412"},
    {"ScenarioName_obj5", "Breakdown Road: Final Challenge!", "KillerRoadNoCapExStage", "obj5"},
    {"ScenarioName_obj3", "Breakdown Road: Hurry!", "KillerRoadNoCapExStage", "obj3"},
    {"ScenarioName_obj2659", "Taking Notes: In the Folding Screen", "SkyWorldCostumeStage", "obj2659"},
    {"ScenarioName_obj2573", "Scene of Crossing the Poison Swamp", "SkyWorldCostumeStage", "obj2573"},
    {"ScenarioName_obj9", "Tussle in Tostarena: Rematch", "RevengeBossKnuckleStage", "obj9"},
    {"ScenarioName_obj668", "Yoshi's Feast in the Sea of Clouds", "YoshiCloudExStage", "obj668"},
    {"ScenarioName_obj903", "Sunken Star in the Sea of Clouds", "YoshiCloudExStage", "obj903"},
    {"ScenarioName_obj13", "Taking Notes: In the Cliffside", "LakeWorld2DZone", "obj13"},
    {"ScenarioName_obj27", "Shopping in Mount Volbono", "LavaWorldShopStage", "obj27"},
    {"ScenarioName_obj1383", "Herding Sheep on the Iron Bridge", "AnimalChaseExStage", "obj1383"},
    {"ScenarioName_obj552", "Herding Sheep Above the Forest Fog", "AnimalChaseExStage", "obj552"},
    {"ScenarioName_obj199", "Around the Barrier Wall", "MoonWorldCaptureParadeKillerZone", "obj199"},
    {"ScenarioName_obj296", "On Top of the Cannon", "MoonWorldCaptureParadeKillerZone", "obj296"},
    {"ScenarioName_obj265", "Hidden Room in the Inverted Pyramid", "SandWorldPyramid001Stage", "obj265"},
    {"ScenarioName_obj2315", "Stone Wall Circuit", "SkyWorldWallZone", "obj2315"},
    {"ScenarioName_obj1671", "Smart Bombing", "SkyWorldWallZone", "obj1671"},
    {"ScenarioName_obj1690", "From the Side Above the Castle Gate", "SkyWorldWallZone", "obj1690"},
    {"ScenarioName_obj2165", "Poking the Turret Wall", "SkyWorldWallZone", "obj2165"},
    {"ScenarioName_obj1179", "Treasure Inside the Turret", "SkyWorldWallZone", "obj1179"},
    {"ScenarioName_obj61", "Back Way Up the Mountain", "ForestWorld2DRoadZone", "obj61"},
    {"ScenarioName_obj438", "Excavate 'n' Search the Cheese Rocks", "LavaWorldExcavationExStage", "obj438"},
    {"ScenarioName_obj629", "Climb the Cheese Rocks", "LavaWorldExcavationExStage", "obj629"},
    {"ScenarioName_obj328", "Invisible Road: Hidden Room", "PackunPoisonExStage", "obj328"},
    {"ScenarioName_obj112", "Invisible Road: Danger!", "PackunPoisonExStage", "obj112"},
    {"ScenarioName_obj4456", "Waves of Poison: Hoppin' Over", "FrogPoisonExStage", "obj4456"},
    {"ScenarioName_obj4547", "Waves of Poison: Hop to It!", "FrogPoisonExStage", "obj4547"},
    {"ScenarioName_obj340", "Iceburn Circuit Class A", "SnowWorldLobbyExStage", "obj340"},
    {"ScenarioName_obj950", "Iceburn Circuit Class S", "SnowWorldLobbyExStage", "obj950"},
    {"ScenarioName_obj345", "Fly to the Treasure Chest and Back", "MoonWorldCaptureParadeStage", "obj345"},
    {"ScenarioName_obj246", "Under the Bowser Statue", "MoonWorldCaptureParadeStage", "obj246"},
    {"ScenarioName_obj5", "Vanishing Road Challenge", "BikeSteelNoCapExStage", "obj5"},
    {"ScenarioName_obj6", "Vanishing Road Rush", "BikeSteelNoCapExStage", "obj6"},
    {"ScenarioName_obj493", "Up on the Big Screen", "Theater2DExStage", "obj493"},
    {"ScenarioName_obj1015", "Down Inside the Big Screen", "Theater2DExStage", "obj1015"},
    {"ScenarioName_obj684", "Forgotten in the Holding Room", "SnowWorldLobby000Stage", "obj684"},
    {"ScenarioName_obj943", "Snowline Circuit Class S", "SnowWorldLobby000Stage", "obj943"},
    {"ScenarioName_obj951", "Hat-and-Seek in the Snow", "SnowWorldLobby000Stage", "obj951"},
    {"ScenarioName_obj743", "Magma Narrow Path", "LavaWorldBubbleLaneExStage", "obj743"},
    {"ScenarioName_obj414", "Crossing to the Magma", "LavaWorldBubbleLaneExStage", "obj414"},
    {"ScenarioName_obj12", "Shopping in Lake Lamode", "LakeWorldShopStage", "obj12"},
    {"ScenarioName_obj154", "Crossing the Cloud Sea", "CloudWorldHomeStage", "obj154"},
    {"ScenarioName_obj156", "Digging in the...Cloud?", "CloudWorldHomeStage", "obj156"},
    {"ScenarioName_obj138", "High, High Above the Clouds", "CloudWorldHomeStage", "obj138"},
    {"ScenarioName_obj130", "Peach in the Cloud Kingdom", "CloudWorldHomeStage", "obj130"},
    {"ScenarioName_obj392", "Taking Notes: Up and Down", "CloudWorldHomeStage", "obj392"},
    {"ScenarioName_obj21", "Shopping Near Peach's Castle", "PeachWorldShopStage", "obj21"},
    {"ScenarioName_obj21", "Wriggling on the Sandy Bottom", "SeaWorldSneakingManStage", "obj21"},
    {"ScenarioName_obj60", "The Seal Above the Canyon", "SeaWorldDamageBallZone", "obj60"},
    {"ScenarioName_obj144", "Love by the Seaside", "SeaWorldDamageBallZone", "obj144"},
    {"ScenarioName_obj220", "Stretching Your Legs", "ForestWorldTowerStage", "obj220"},
    {"ScenarioName_obj161", "Nut Planted in the Tower", "ForestWorldTowerStage", "obj161"},
    {"ScenarioName_obj76", "Climb the Wooden Tower", "TsukkunClimbExStage", "obj76"},
    {"ScenarioName_obj19", "Poke the Wooden Tower", "TsukkunClimbExStage", "obj19"},
    {"ScenarioName_obj460", "In a Hole in the Magma", "MoonWorldCaptureParadeLavaPillarZone", "obj460"},
    {"ScenarioName_obj19", "Shopping on Forgotten Isle", "ClashWorldShopStage", "obj19"},
    {"ScenarioName_obj36", "Shopping at Bowser's Castle", "SkyWorldShopStage", "obj36"},
    {"ScenarioName_obj6", "Defend the Secret Flower Field!", "ForestWorldBossStage", "obj6"},
    {"ScenarioName_obj488", "Make the Secret Flower Field Bloom", "ForestWorldBossStage", "obj488"},
    {"ScenarioName_obj38", "King of the Cube!", "Cube2DExStage", "obj38"},
    {"ScenarioName_obj251", "The Sixth Face", "Cube2DExStage", "obj251"},
    {"ScenarioName_obj247", "High Over the Crowd", "CityPeopleRoadStage", "obj247"},
    {"ScenarioName_obj1379", "Hat-and-Seek: In the Crowd", "CityPeopleRoadStage", "obj1379"},
    {"ScenarioName_obj1390", "Pushing Through the Crowd", "CityPeopleRoadStage", "obj1390"},
    {"ScenarioName_obj800", "Fly Through the Narrow Valley", "WaterValleyExStage", "obj800"},
    {"ScenarioName_obj1125", "Treasure Chest in the Narrow Valley", "WaterValleyExStage", "obj1125"},
    {"ScenarioName_obj6", "Struggle in Steam Gardens: Rematch", "RevengeForestBossStage", "obj6"},
    {"ScenarioName_obj103", "Swinging Scaffolding: Break!", "SwingSteelExStage", "obj103"},
    {"ScenarioName_obj39", "Swinging Scaffolding: Jump!", "SwingSteelExStage", "obj39"},
    {"ScenarioName_obj21", "A Relaxing Dance", "SeaWorldCostumeStage", "obj21"},
    {"ScenarioName_obj16", "The Lighthouse Seal", "SeaWorldLighthouseZone", "obj16"},
    {"ScenarioName_obj406", "At the Base of the Lighthouse", "SeaWorldLighthouseZone", "obj406"},
    {"ScenarioName_obj407", "A Light Next to the Lighthouse", "SeaWorldLighthouseZone", "obj407"},
    {"ScenarioName_obj113", "Beneath the Rolling Vegetables", "LavaWorldIslandZone", "obj113"},
    {"ScenarioName_obj314", "All the Cracks Are Fixed", "LavaWorldIslandZone", "obj314"},
    {"ScenarioName_obj54", "Dust-Up in New Donk City: Rematch", "RevengeMofumofuStage", "obj54"},
    {"ScenarioName_obj320", "Taking Notes: Spinning Athletics", "LavaWorldClockExStage", "obj320"},
    {"ScenarioName_obj544", "Spinning Athletics End Goal", "LavaWorldClockExStage", "obj544"},
    {"ScenarioName_obj92", "Sphynx's Treasure Vault", "SandWorldSecretStage", "obj92"},
    {"ScenarioName_obj29", "Metro Kingdom Slots", "CityWorldSandSlotStage", "obj29"},
    {"ScenarioName_obj901", "Taking Notes: In the Private Room", "Note2D3DRoomExStage", "obj901"},
    {"ScenarioName_obj249", "Secrets of the Frog Pond", "FrogSearchExStage", "obj249"},
    {"ScenarioName_obj106", "Searching the Frog Pond", "FrogSearchExStage", "obj106"},
    {"ScenarioName_obj193", "Push-Block Peril", "PushBlockExStage", "obj193"},
    {"ScenarioName_obj463", "Hidden Among the Push-Blocks", "PushBlockExStage", "obj463"},
    {"ScenarioName_obj130", "Arrival at Rabbit Ridge!", "Special1WorldHomeStage", "obj130"},
    {"ScenarioName_obj480", "Found with Dark Side Art 7", "Special1WorldHomeStage", "obj480"},
    {"ScenarioName_obj482", "Found with Dark Side Art 6", "Special1WorldHomeStage", "obj482"},
    {"ScenarioName_obj485", "Found with Dark Side Art 9", "Special1WorldHomeStage", "obj485"},
    {"ScenarioName_obj469", "Captain Toad on the Dark Side!", "Special1WorldHomeStage", "obj469"},
    {"ScenarioName_obj486", "Found with Dark Side Art 5", "Special1WorldHomeStage", "obj486"},
    {"ScenarioName_obj487", "Found with Dark Side Art 2", "Special1WorldHomeStage", "obj487"},
    {"ScenarioName_obj488", "Found with Dark Side Art 3", "Special1WorldHomeStage", "obj488"},
    {"ScenarioName_obj489", "Found with Dark Side Art 1", "Special1WorldHomeStage", "obj489"},
    {"ScenarioName_obj475", "Found with Dark Side Art 8", "Special1WorldHomeStage", "obj475"},
    {"ScenarioName_obj476", "Found with Dark Side Art 4", "Special1WorldHomeStage", "obj476"},
    {"ScenarioName_obj478", "Found with Dark Side Art 10", "Special1WorldHomeStage", "obj478"},
    {"ScenarioName_obj69", "Blowing and Sliding", "ByugoPuzzleExStage", "obj69"},
    {"ScenarioName_obj2288", "Dashing Through the Clouds", "SkyWorldCloudBonusExStage", "obj2288"},
    {"ScenarioName_obj1581", "Dashing Above the Clouds", "SkyWorldCloudBonusExStage", "obj1581"},
    {"ScenarioName_obj82", "A Swing on Top of a Swing", "MoonAthleticExStage", "obj82"},
    {"ScenarioName_obj53", "Navigating Giant Swings", "MoonAthleticExStage", "obj53"},
    {"ScenarioName_obj41", "Wooded Kingdom Timer Challenge 2", "ForestWorldTimerAthletic001Zone", "obj41"},
    {"ScenarioName_obj4", "Precision Rolling", "RollingExStage", "obj4"},
    {"ScenarioName_obj11", "Roll On and On", "RollingExStage", "obj11"},
    {"ScenarioName_obj659", "Vaulting Up a High-Rise", "PoleGrabCeilExStage", "obj659"},
    {"ScenarioName_obj301", "Hanging from a High-Rise", "PoleGrabCeilExStage", "obj301"},
    {"ScenarioName_obj343", "Glowing in the Deep Woods", "ForestWorldWoodsStage", "obj343"},
    {"ScenarioName_obj392", "A Treasure Made from Coins", "ForestWorldWoodsStage", "obj392"},
    {"ScenarioName_obj415", "Past the Peculiar Pipes", "ForestWorldWoodsStage", "obj415"},
    {"ScenarioName_obj206", "The Hard Rock in Deep Woods", "ForestWorldWoodsStage", "obj206"},
    {"ScenarioName_obj186", "By the Babbling Brook in Deep Woods", "ForestWorldWoodsStage", "obj186"},
    {"ScenarioName_obj220", "Rolling Rock in the Deep Woods", "ForestWorldWoodsStage", "obj220"},
    {"ScenarioName_obj222", "Beneath the Roots of the Moving Tree", "ForestWorldWoodsStage", "obj222"},
    {"ScenarioName_obj179", "Outside the Rotating Maze", "CapRotatePackunExStage", "obj179"},
    {"ScenarioName_obj84", "Inside the Rotating Maze", "CapRotatePackunExStage", "obj84"},
    {"ScenarioName_obj450", "Moon Shards in the Cold Room", "SnowWorldCostumeStage", "obj450"},
    {"ScenarioName_obj733", "Slip Behind the Ice", "SnowWorldCostumeStage", "obj733"},
    {"ScenarioName_obj1117", "Jump, Grab, Cling, and Climb", "TrampolineWallCatchExStage", "obj1117"},
    {"ScenarioName_obj1238", "Jump, Grab, and Climb Some More", "TrampolineWallCatchExStage", "obj1238"},
    {"ScenarioName_obj4", "Ride the Jetstream", "SeaWorldWallCaveCenterZone", "obj4"},
    {"ScenarioName_obj4591", "Swaying in the Breeze", "CityWorldHomeStage", "obj4591"},
    {"ScenarioName_obj7051", "Drummer on Board!", "CityWorldHomeStage", "obj7051"},
    {"ScenarioName_obj14592", "Free Parking: Leap of Faith", "CityWorldHomeStage", "obj14592"},
    {"ScenarioName_obj13924", "Free Parking: Rooftop Hop", "CityWorldHomeStage", "obj13924"},
    {"ScenarioName_obj13616", "Bench Friends", "CityWorldHomeStage", "obj13616"},
    {"ScenarioName_obj7058", "Trumpeter on Board!", "CityWorldHomeStage", "obj7058"},
    {"ScenarioName_obj2782", "Jump-Rope Genius", "CityWorldHomeStage", "obj2782"},
    {"ScenarioName_obj9072", "Bassist on Board!", "CityWorldHomeStage", "obj9072"},
    {"ScenarioName_obj10646", "Dizzying Heights", "CityWorldHomeStage", "obj10646"},
    {"ScenarioName_obj3066", "Remotely Captured Car", "CityWorldHomeStage", "obj3066"},
    {"ScenarioName_obj13419", "Glittering Above the Pool", "CityWorldHomeStage", "obj13419"},
    {"ScenarioName_obj14342", "Jammin' in the Metro Kingdom", "CityWorldHomeStage", "obj14342"},
    {"ScenarioName_obj3633", "How You Doin', Captain Toad?", "CityWorldHomeStage", "obj3633"},
    {"ScenarioName_obj15040", "Found with Metro Kingdom Art", "CityWorldHomeStage", "obj15040"},
    {"ScenarioName_obj12584", "Left at the Cafe?", "CityWorldHomeStage", "obj12584"},
    {"ScenarioName_obj12585", "Out of a Crate in the City", "CityWorldHomeStage", "obj12585"},
    {"ScenarioName_obj12586", "Crossing Lines", "CityWorldHomeStage", "obj12586"},
    {"ScenarioName_obj11212", "Hidden in the Scrap", "CityWorldHomeStage", "obj11212"},
    {"ScenarioName_obj12589", "Hat-and-Seek: In the City", "CityWorldHomeStage", "obj12589"},
    {"ScenarioName_obj14877", "Sphynx in the City", "CityWorldHomeStage", "obj14877"},
    {"ScenarioName_obj6939", "A Request from the Mayor", "CityWorldHomeStage", "obj6939"},
    {"ScenarioName_obj10046", "Secret Girder Tunnel!", "CityWorldHomeStage", "obj10046"},
    {"ScenarioName_obj14258", "Surprise Clown!", "CityWorldHomeStage", "obj14258"},
    {"ScenarioName_obj4110", "A Traditional Festival!", "CityWorldHomeStage", "obj4110"},
    {"ScenarioName_obj14420", "Metro Kingdom Master Cup", "CityWorldHomeStage", "obj14420"},
    {"ScenarioName_obj7046", "Guitarist on Board!", "CityWorldHomeStage", "obj7046"},
    {"ScenarioName_obj13457", "Caught Hopping on a Building!", "CityWorldHomeStage", "obj13457"},
    {"ScenarioName_obj15743", "Bird Traveling in the City", "CityWorldHomeStage", "obj15743"},
    {"ScenarioName_obj14384", "Metro Kingdom Timer Challenge 3", "CityWorldHomeStage", "obj14384"},
    {"ScenarioName_obj10635", "Jump-Rope Hero", "CityWorldHomeStage", "obj10635"},
    {"ScenarioName_obj4956", "How Do They Take Out the Trash?", "CityWorldHomeStage", "obj4956"},
    {"ScenarioName_obj3203", "New Donk City's Pest Problem", "CityWorldHomeStage", "obj3203"},
    {"ScenarioName_obj8895", "Secret Path to New Donk City!", "CityWorldHomeStage", "obj8895"},
    {"ScenarioName_obj10124", "City Gardening: Rooftop Planter", "CityWorldHomeStage", "obj10124"},
    {"ScenarioName_obj13473", "Peach in the Metro Kingdom", "CityWorldHomeStage", "obj13473"},
    {"ScenarioName_obj13057", "Mario Signs His Name", "CityWorldHomeStage", "obj13057"},
    {"ScenarioName_obj10126", "City Gardening: Building Planter", "CityWorldHomeStage", "obj10126"},
    {"ScenarioName_obj8073", "Who Piled Garbage on This?", "CityWorldHomeStage", "obj8073"},
    {"ScenarioName_obj10128", "City Gardening: Plaza Planter", "CityWorldHomeStage", "obj10128"},
    {"ScenarioName_obj4448", "Inside an Iron Girder", "CityWorldHomeStage", "obj4448"},
    {"ScenarioName_obj12578", "A Tourist in the Metro Kingdom!", "CityWorldHomeStage", "obj12578"},
    {"ScenarioName_obj3116", "Girder Sandwich", "CityWorldHomeStage", "obj3116"},
    {"ScenarioName_obj16048", "Bird Traveling in the Park", "CityWorldHomeStage", "obj16048"},
    {"ScenarioName_obj12590", "Found in the Park! Good Dog!", "CityWorldHomeStage", "obj12590"},
    {"ScenarioName_obj12592", "Hanging Between Buildings", "CityWorldHomeStage", "obj12592"},
    {"ScenarioName_obj14411", "Metro Kingdom Regular Cup", "CityWorldHomeStage", "obj14411"},
    {"ScenarioName_obj15", "A Rumble on the Seaside Floor", "SeaWorldVibrationStage", "obj15"},
    {"ScenarioName_obj14", "Exploring for Treasure", "ForestWorldWoodsCostumeStage", "obj14"},
    {"ScenarioName_obj175", "Lake Kingdom Timer Challenge 2", "LakeWorldTimerAthletic000Zone", "obj175"},
    {"ScenarioName_obj463", "Underground Treasure Chest", "SandWorldUnderground000Stage", "obj463"},
    {"ScenarioName_obj352", "Goomba Tower Assembly", "SandWorldUnderground000Stage", "obj352"},
    {"ScenarioName_obj105", "Elevator Escalation", "ShootingElevatorExStage", "obj105"},
    {"ScenarioName_obj160", "Elevator Blind Spot", "ShootingElevatorExStage", "obj160"},
    {"ScenarioName_obj34", "Sand Kingdom Slots", "SandWorldSlotStage", "obj34"},
    {"ScenarioName_obj2710", "Frog-Jumping Above the Fog", "CapWorldHomeStage", "obj2710"},
    {"ScenarioName_obj2207", "Peach in the Cap Kingdom", "CapWorldHomeStage", "obj2207"},
    {"ScenarioName_obj2730", "Cap Kingdom Regular Cup", "CapWorldHomeStage", "obj2730"},
    {"ScenarioName_obj2789", "Found with Cap Kingdom Art", "CapWorldHomeStage", "obj2789"},
    {"ScenarioName_obj2420", "Fog-Shrouded Platform", "CapWorldHomeStage", "obj2420"},
    {"ScenarioName_obj2422", "Frog-Jumping from the Top Deck", "CapWorldHomeStage", "obj2422"},
    {"ScenarioName_obj2423", "Danger Sign", "CapWorldHomeStage", "obj2423"},
    {"ScenarioName_obj2424", "Under the Big One's Brim", "CapWorldHomeStage", "obj2424"},
    {"ScenarioName_obj2739", "Bonneter Blockade", "CapWorldHomeStage", "obj2739"},
    {"ScenarioName_obj2444", "Cap Kingdom Timer Challenge 1", "CapWorldHomeStage", "obj2444"},
    {"ScenarioName_obj820", "Hidden in a Sunken Hat", "CapWorldHomeStage", "obj820"},
    {"ScenarioName_obj2972", "Bird Traveling in the Fog", "CapWorldHomeStage", "obj2972"},
    {"ScenarioName_obj2975", "Fly to the Edge of the Fog", "CapWorldHomeStage", "obj2975"},
    {"ScenarioName_obj2249", "Next to Glasses Bridge", "CapWorldHomeStage", "obj2249"},
    {"ScenarioName_obj2771", "Taxi Flying Through Bonneton", "CapWorldHomeStage", "obj2771"},
    {"ScenarioName_obj2611", "Cap Kingdom Timer Challenge 2", "CapWorldHomeStage", "obj2611"},
    {"ScenarioName_obj2721", "Spin the Hat, Get a Prize", "CapWorldHomeStage", "obj2721"},
    {"ScenarioName_obj2681", "Taking Notes: In the Fog", "CapWorldHomeStage", "obj2681"},
    {"ScenarioName_obj2268", "The Forgotten Treasure", "CapWorldHomeStage", "obj2268"},
    {"ScenarioName_obj2729", "Cap Kingdom Master Cup", "CapWorldHomeStage", "obj2729"},
    {"ScenarioName_obj2196", "Caught Hopping Near the Ship!", "CapWorldHomeStage", "obj2196"},
    {"ScenarioName_obj926", "Good Evening, Captain Toad!", "CapWorldHomeStage", "obj926"},
    {"ScenarioName_obj882", "Shopping in Bonneton", "CapWorldHomeStage", "obj882"},
    {"ScenarioName_obj19", "Dancing with New Friends", "SandWorldCostumeStage", "obj19"},
    {"ScenarioName_obj76", "On Top of the Spinning Tower", "TsukkunRotateExStage", "obj76"},
    {"ScenarioName_obj149", "Down and Up the Spinning Tower", "TsukkunRotateExStage", "obj149"},
    {"ScenarioName_obj18", "Walking on Ice!", "IceWalkerExStage", "obj18"},
    {"ScenarioName_obj19", "Even More Walking on Ice!", "IceWalkerExStage", "obj19"},
    {"ScenarioName_obj187", "Up in the Rafters", "MoonWorldWeddingRoomStage", "obj187"},
    {"ScenarioName_obj1423", "Snow Kingdom Master Cup", "SnowWorldHomeStage", "obj1423"},
    {"ScenarioName_obj1459", "I Met a Snow Cheep Cheep!", "SnowWorldHomeStage", "obj1459"},
    {"ScenarioName_obj769", "Moon Shards in the Snow", "SnowWorldHomeStage", "obj769"},
    {"ScenarioName_obj1507", "Snow Kingdom Timer Challenge 3", "SnowWorldHomeStage", "obj1507"},
    {"ScenarioName_obj1049", "Taking Notes: Snow Path Dash", "SnowWorldHomeStage", "obj1049"},
    {"ScenarioName_obj1491", "Caught Hopping in the Snow!", "SnowWorldHomeStage", "obj1491"},
    {"ScenarioName_obj1338", "Captain Toad is Chilly!", "SnowWorldHomeStage", "obj1338"},
    {"ScenarioName_obj1113", "Shining on High", "SnowWorldHomeStage", "obj1113"},
    {"ScenarioName_obj1115", "Deep in the Cold, Cold Water", "SnowWorldHomeStage", "obj1115"},
    {"ScenarioName_obj581", "Ice Floe Swimming", "SnowWorldHomeStage", "obj581"},
    {"ScenarioName_obj1116", "Above the Freezing Fishing Pond", "SnowWorldHomeStage", "obj1116"},
    {"ScenarioName_obj1431", "Secret Path to Shiveria!", "SnowWorldHomeStage", "obj1431"},
    {"ScenarioName_obj1117", "It Popped Out of the Ice", "SnowWorldHomeStage", "obj1117"},
    {"ScenarioName_obj1086", "Fishing in the Glacier!", "SnowWorldHomeStage", "obj1086"},
    {"ScenarioName_obj1309", "Snow Kingdom Timer Challenge 1", "SnowWorldHomeStage", "obj1309"},
    {"ScenarioName_obj1321", "Snow Kingdom Timer Challenge 2", "SnowWorldHomeStage", "obj1321"},
    {"ScenarioName_obj1359", "Snow Kingdom Regular Cup", "SnowWorldHomeStage", "obj1359"},
    {"ScenarioName_obj2455", "Caught Hopping at the Waterfall!", "WaterfallWorldHomeStage", "obj2455"},
    {"ScenarioName_obj1526", "Across the Floating Isles", "WaterfallWorldHomeStage", "obj1526"},
    {"ScenarioName_obj2618", "Cascade Kingdom Timer Challenge 1", "WaterfallWorldHomeStage", "obj2618"},
    {"ScenarioName_obj3284", "On Top of the Rubble", "WaterfallWorldHomeStage", "obj3284"},
    {"ScenarioName_obj2898", "Caveman Cave-Fan", "WaterfallWorldHomeStage", "obj2898"},
    {"ScenarioName_obj2741", "Cascade Kingdom Regular Cup", "WaterfallWorldHomeStage", "obj2741"},
    {"ScenarioName_obj2821", "Under the Old Electrical Pole", "WaterfallWorldHomeStage", "obj2821"},
    {"ScenarioName_obj3523", "Inside the Busted Fossil", "WaterfallWorldHomeStage", "obj3523"},
    {"ScenarioName_obj2490", "Above a High Cliff", "WaterfallWorldHomeStage", "obj2490"},
    {"ScenarioName_obj2823", "Guarded by a Colossal Fossil", "WaterfallWorldHomeStage", "obj2823"},
    {"ScenarioName_obj2824", "Just a Hat, Skip, and a Jump", "WaterfallWorldHomeStage", "obj2824"},
    {"ScenarioName_obj214", "Our First Power Moon", "WaterfallWorldHomeStage", "obj214"},
    {"ScenarioName_obj1033", "Secret Path to Fossil Falls!", "WaterfallWorldHomeStage", "obj1033"},
    {"ScenarioName_obj124", "Behind the Waterfall", "WaterfallWorldHomeStage", "obj124"},
    {"ScenarioName_obj1119", "Shopping in Fossil Falls", "WaterfallWorldHomeStage", "obj1119"},
    {"ScenarioName_obj2423", "A Tourist in the Cascade Kingdom", "WaterfallWorldHomeStage", "obj2423"},
    {"ScenarioName_obj21", "Multi Moon Atop the Falls", "WaterfallWorldHomeStage", "obj21"},
    {"ScenarioName_obj2819", "Under the Ground", "WaterfallWorldHomeStage", "obj2819"},
    {"ScenarioName_obj3110", "Rolling Rock by the Falls", "WaterfallWorldHomeStage", "obj3110"},
    {"ScenarioName_obj3208", "Sphynx Traveling to the Waterfall", "WaterfallWorldHomeStage", "obj3208"},
    {"ScenarioName_obj1027", "Bottom of the Waterfall Basin", "WaterfallWorldHomeStage", "obj1027"},
    {"ScenarioName_obj1028", "Treasure Under the Cliff", "WaterfallWorldHomeStage", "obj1028"},
    {"ScenarioName_obj1717", "Good Morning, Captain Toad!", "WaterfallWorldHomeStage", "obj1717"},
    {"ScenarioName_obj1029", "Next to the Stone Arch", "WaterfallWorldHomeStage", "obj1029"},
    {"ScenarioName_obj2691", "Cascade Kingdom Timer Challenge 2", "WaterfallWorldHomeStage", "obj2691"},
    {"ScenarioName_obj2947", "Cascade Kingdom Master Cup", "WaterfallWorldHomeStage", "obj2947"},
    {"ScenarioName_obj2778", "Taking Notes: Hurry Upward", "WaterfallWorldHomeStage", "obj2778"},
    {"ScenarioName_obj1928", "Treasure of the Waterfall Basin", "WaterfallWorldHomeStage", "obj1928"},
    {"ScenarioName_obj2467", "Peach in the Cascade Kingdom", "WaterfallWorldHomeStage", "obj2467"},
    {"ScenarioName_obj407", "Chomp Through the Rocks", "WaterfallWorldHomeStage", "obj407"},
    {"ScenarioName_obj49", "The Bullet Bill Maze: Side Path", "SandWorldKillerExStage", "obj49"},
    {"ScenarioName_obj127", "The Bullet Bill Maze: Break Through!", "SandWorldKillerExStage", "obj127"},
    {"ScenarioName_obj68", "Slip Through the Nesting Spot", "SeaWorldUtsuboDenZone", "obj68"},
    {"ScenarioName_obj132", "Magma Swamp: Floating and Sinking", "LavaWorldUpDownExStage", "obj132"},
    {"ScenarioName_obj430", "Corner of the Magma Swamp", "LavaWorldUpDownExStage", "obj430"},
    {"ScenarioName_obj346", "Celebrating in the Streets!", "CityWorld2DSign004Zone", "obj346"},
    {"ScenarioName_obj999", "Treasure of the Lava Islands", "LavaWorldFenceLiftExStage", "obj999"},
    {"ScenarioName_obj104", "Flying Over the Lava Islands", "LavaWorldFenceLiftExStage", "obj104"},
    {"ScenarioName_obj5760", "High-Altitude Spinning", "SnowWorldCloudBonusExStage", "obj5760"},
    {"ScenarioName_obj5375", "Spinning Above the Clouds", "SnowWorldCloudBonusExStage", "obj5375"},
    {"ScenarioName_obj281", "Squirming Under Ice", "SnowWorldBalconyZone", "obj281"},
    {"ScenarioName_obj89", "Behind Snowy Mountain", "SnowWorldBalconyZone", "obj89"},
    {"ScenarioName_obj719", "Stepping Over the Gears", "GabuzouClockExStage", "obj719"},
    {"ScenarioName_obj439", "Lanterns on the Gear Steps", "GabuzouClockExStage", "obj439"},
    {"ScenarioName_obj331", "The Bound Bowl Grand Prix", "SnowWorldLobby001Stage", "obj331"},
    {"ScenarioName_obj2083", "Aim! Poke!", "ReflectBombExStage", "obj2083"},
    {"ScenarioName_obj2157", "Poke! Roll!", "ReflectBombExStage", "obj2157"},
    {"ScenarioName_obj2143", "Bird Traveling the Desert", "SandWorldHomeStage", "obj2143"},
    {"ScenarioName_obj6126", "Love at the Edge of the Desert", "SandWorldHomeStage", "obj6126"},
    {"ScenarioName_obj1432", "Showdown on the Inverted Pyramid", "SandWorldHomeStage", "obj1432"},
    {"ScenarioName_obj2874", "Desert Gardening: Plaza Seed", "SandWorldHomeStage", "obj2874"},
    {"ScenarioName_obj576", "Alcove in the Ruins", "SandWorldHomeStage", "obj576"},
    {"ScenarioName_obj2875", "Desert Gardening: Ruins Seed", "SandWorldHomeStage", "obj2875"},
    {"ScenarioName_obj2876", "Desert Gardening: Seed on the Cliff", "SandWorldHomeStage", "obj2876"},
    {"ScenarioName_obj1599", "Atop the Highest Tower", "SandWorldHomeStage", "obj1599"},
    {"ScenarioName_obj5335", "More Walking in the Desert!", "SandWorldHomeStage", "obj5335"},
    {"ScenarioName_obj4392", "Bird Traveling the Wastes", "SandWorldHomeStage", "obj4392"},
    {"ScenarioName_obj481", "Fishing in the Oasis", "SandWorldHomeStage", "obj481"},
    {"ScenarioName_obj3371", "Hidden Room in the Flowing Sands", "SandWorldHomeStage", "obj3371"},
    {"ScenarioName_obj3998", "Found in the Sand! Good Dog!", "SandWorldHomeStage", "obj3998"},
    {"ScenarioName_obj3999", "Top of a Dune", "SandWorldHomeStage", "obj3999"},
    {"ScenarioName_obj4807", "Sand Kingdom Timer Challenge 3", "SandWorldHomeStage", "obj4807"},
    {"ScenarioName_obj123", "On the Leaning Pillar", "SandWorldHomeStage", "obj123"},
    {"ScenarioName_obj3431", "An Invisible Gleam", "SandWorldHomeStage", "obj3431"},
    {"ScenarioName_obj1609", "Walking the Desert!", "SandWorldHomeStage", "obj1609"},
    {"ScenarioName_obj3433", "Poster Cleanup", "SandWorldHomeStage", "obj3433"},
    {"ScenarioName_obj1715", "Sand Quiz: Wonderful!", "SandWorldHomeStage", "obj1715"},
    {"ScenarioName_obj3434", "On the North Pillar", "SandWorldHomeStage", "obj3434"},
    {"ScenarioName_obj3437", "Mighty Leap from the Palm Tree!", "SandWorldHomeStage", "obj3437"},
    {"ScenarioName_obj6057", "Jammin' in the Sand Kingdom", "SandWorldHomeStage", "obj6057"},
    {"ScenarioName_obj6059", "Hat-and-Seek: In the Sand", "SandWorldHomeStage", "obj6059"},
    {"ScenarioName_obj6208", "Sand Kingdom Regular Cup", "SandWorldHomeStage", "obj6208"},
    {"ScenarioName_obj6209", "Sand Kingdom Master Cup", "SandWorldHomeStage", "obj6209"},
    {"ScenarioName_obj6270", "Jaxi Reunion!", "SandWorldHomeStage", "obj6270"},
    {"ScenarioName_obj5267", "The Lurker Under the Stone", "SandWorldHomeStage", "obj5267"},
    {"ScenarioName_obj2188", "Taking Notes: Running Down", "SandWorldHomeStage", "obj2188"},
    {"ScenarioName_obj4000", "Where the Birds Gather", "SandWorldHomeStage", "obj4000"},
    {"ScenarioName_obj980", "On Top of the Stone Archway", "SandWorldHomeStage", "obj980"},
    {"ScenarioName_obj4001", "Lost in the Luggage", "SandWorldHomeStage", "obj4001"},
    {"ScenarioName_obj4059", "Inside a Block Is a Hard Place", "SandWorldHomeStage", "obj4059"},
    {"ScenarioName_obj4002", "Wandering Cactus", "SandWorldHomeStage", "obj4002"},
    {"ScenarioName_obj5320", "You're Quite a Catch, Captain Toad!", "SandWorldHomeStage", "obj5320"},
    {"ScenarioName_obj4271", "Hang Your Hat on the Fountain", "SandWorldHomeStage", "obj4271"},
    {"ScenarioName_obj878", "Bullet Bill Breakthrough", "SandWorldHomeStage", "obj878"},
    {"ScenarioName_obj4272", "On the Statue's Tail", "SandWorldHomeStage", "obj4272"},
    {"ScenarioName_obj1841", "Herding Sheep in the Dunes", "SandWorldHomeStage", "obj1841"},
    {"ScenarioName_obj3456", "Love in the Heart of the Desert", "SandWorldHomeStage", "obj3456"},
    {"ScenarioName_obj4277", "'Round-the-World Tourist", "SandWorldHomeStage", "obj4277"},
    {"ScenarioName_obj2047", "Secret of the Inverted Mural", "SandWorldHomeStage", "obj2047"},
    {"ScenarioName_obj3782", "Taking Notes: Jump on the Palm", "SandWorldHomeStage", "obj3782"},
    {"ScenarioName_obj4187", "On the Eastern Pillar", "SandWorldHomeStage", "obj4187"},
    {"ScenarioName_obj6244", "Found with Sand Kingdom Art", "SandWorldHomeStage", "obj6244"},
    {"ScenarioName_obj2888", "On the Lone Pillar", "SandWorldHomeStage", "obj2888"},
    {"ScenarioName_obj3735", "Moon Shards in the Sand", "SandWorldHomeStage", "obj3735"},
    {"ScenarioName_obj536", "Overlooking the Desert Town", "SandWorldHomeStage", "obj536"},
    {"ScenarioName_obj4555", "Peach in the Sand Kingdom", "SandWorldHomeStage", "obj4555"},
    {"ScenarioName_obj3387", "Secret Path to Tostarena!", "SandWorldHomeStage", "obj3387"},
    {"ScenarioName_obj902", "From a Crate in the Ruins", "SandWorldHomeStage", "obj902"},
    {"ScenarioName_obj3389", "The Treasure of Jaxi Ruins", "SandWorldHomeStage", "obj3389"},
    {"ScenarioName_obj5364", "Into the Flowing Sands", "SandWorldHomeStage", "obj5364"},
    {"ScenarioName_obj5989", "Among the Five Cactuses", "SandWorldHomeStage", "obj5989"},
    {"ScenarioName_obj3442", "In the Skies Above the Canyon", "SandWorldHomeStage", "obj3442"},
    {"ScenarioName_obj2230", "Island in the Poison Swamp", "SandWorldHomeStage", "obj2230"},
    {"ScenarioName_obj5206", "Welcome Back, Jaxi!", "SandWorldHomeStage", "obj5206"},
    {"ScenarioName_obj4685", "Sand Kingdom Timer Challenge 2", "SandWorldHomeStage", "obj4685"},
    {"ScenarioName_obj4483", "Caught Hopping in the Desert!", "SandWorldHomeStage", "obj4483"},
    {"ScenarioName_obj4632", "Sand Kingdom Timer Challenge 1", "SandWorldHomeStage", "obj4632"},
    {"ScenarioName_obj18", "Dinosaur Nest: Big Cleanup!", "TrexPoppunExStage", "obj18"},
    {"ScenarioName_obj169", "Dinosaur Nest: Running Wild!", "TrexPoppunExStage", "obj169"},
    {"ScenarioName_obj363", "Freezing Water Near the Ceiling", "IceWaterBlockExStage", "obj363"},
    {"ScenarioName_obj170", "Jump 'n' Swim in the Freezing Water", "IceWaterBlockExStage", "obj170"},
    {"ScenarioName_obj4857", "Aglow in the Jungle", "ImomuPoisonExStage", "obj4857"},
    {"ScenarioName_obj3970", "Stretch and Traverse the Jungle", "ImomuPoisonExStage", "obj3970"},
    {"ScenarioName_obj3056", "Found Behind Bars!", "SkyWorldCastleZone", "obj3056"},
    {"ScenarioName_obj7369", "Found with Bowser's Kingdom Art", "SkyWorldCastleZone", "obj7369"},
    {"ScenarioName_obj3646", "Inside a Block in the Castle", "SkyWorldCastleZone", "obj3646"},
    {"ScenarioName_obj3811", "Big Broodal Battle", "SkyWorldCastleZone", "obj3811"},
    {"ScenarioName_obj5201", "Bowser's Kingdom Timer Challenge 1", "SkyWorldCastleZone", "obj5201"},
    {"ScenarioName_obj8382", "A Rumble Under the Arena Floor", "SkyWorldCastleZone", "obj8382"},
    {"ScenarioName_obj6841", "Bowser's Kingdom Timer Challenge 2", "SkyWorldCastleZone", "obj6841"},
    {"ScenarioName_obj2335", "Good to See You, Captain Toad!", "SkyWorldCastleZone", "obj2335"},
    {"ScenarioName_obj7276", "From Crates in the Moat", "SkyWorldCastleZone", "obj7276"},
    {"ScenarioName_obj649", "On the Giant Bowser Statue's Nose", "SkyWorldCastleZone", "obj649"},
    {"ScenarioName_obj3819", "Showdown at Bowser's Castle", "SkyWorldCastleZone", "obj3819"},
    {"ScenarioName_obj7501", "Taking Notes with a Spinning Throw", "SkyWorldCastleZone", "obj7501"},
    {"ScenarioName_obj7554", "Knocking Down the Nice Frame", "SkyWorldCastleZone", "obj7554"},
    {"ScenarioName_obj2138", "Above the Poison Swamp", "SkyWorldCastleZone", "obj2138"},
    {"ScenarioName_obj4118", "Caught Hopping at Bowser's Castle!", "SkyWorldCastleZone", "obj4118"},
    {"ScenarioName_obj4857", "Fishing(?) in Bowser's Castle", "SkyWorldCastleZone", "obj4857"},
    {"ScenarioName_obj7296", "Sphynx Over Bowser's Castle", "SkyWorldCastleZone", "obj7296"},
    {"ScenarioName_obj2203", "Sunken Treasure in the Moat", "SkyWorldCastleZone", "obj2203"},
    {"ScenarioName_obj3362", "Past the Moving Wall", "SkyWorldCastleZone", "obj3362"},
    {"ScenarioName_obj7421", "Hidden Corridor Under the Floor", "SkyWorldCastleZone", "obj7421"},
    {"ScenarioName_obj6825", "I Met a Pokio!", "SkyWorldCastleZone", "obj6825"},
    {"ScenarioName_obj2320", "Poking Your Nose by the Great Gate", "SkyWorldCastleZone", "obj2320"},
    {"ScenarioName_obj55", "Long Journey's End", "Special2WorldHomeStage", "obj55"},
    {"ScenarioName_obj158", "Unzip the Chasm", "FastenerExStage", "obj158"},
    {"ScenarioName_obj602", "Super-Secret Zipper", "FastenerExStage", "obj602"},
    {"ScenarioName_obj282", "Roulette Tower: Climbed", "DotTowerExStage", "obj282"},
    {"ScenarioName_obj371", "Roulette Tower: Stopped", "DotTowerExStage", "obj371"},
    {"ScenarioName_obj4", "Invisible Road: Rush!", "PackunPoisonNoCapExStage", "obj4"},
    {"ScenarioName_obj9", "Invisible Road: Secret!", "PackunPoisonNoCapExStage", "obj9"},
    {"ScenarioName_obj1186", "Searching Hexagon Tower", "KaronWingTowerStage", "obj1186"},
    {"ScenarioName_obj1190", "Center of Hexagon Tower", "KaronWingTowerStage", "obj1190"},
    {"ScenarioName_obj1593", "Taking Notes: Ocean Surface Dash", "SeaWorldHomeStage", "obj1593"},
    {"ScenarioName_obj3153", "Bird Traveling Over the Ocean", "SeaWorldHomeStage", "obj3153"},
    {"ScenarioName_obj2255", "Found on the Beach! Good Dog!", "SeaWorldHomeStage", "obj2255"},
    {"ScenarioName_obj4391", "Taking Notes in the Sea", "SeaWorldHomeStage", "obj4391"},
    {"ScenarioName_obj3104", "Sea Gardening: Hot-Spring Seed", "SeaWorldHomeStage", "obj3104"},
    {"ScenarioName_obj2580", "What Shines Inside the Glass", "SeaWorldHomeStage", "obj2580"},
    {"ScenarioName_obj2581", "Above the Parasol: Catch!", "SeaWorldHomeStage", "obj2581"},
    {"ScenarioName_obj2112", "Shh! It's a Shortcut!", "SeaWorldHomeStage", "obj2112"},
    {"ScenarioName_obj2225", "Sea Gardening: Ocean Trench Seed", "SeaWorldHomeStage", "obj2225"},
    {"ScenarioName_obj2079", "The Back Canyon: Excavate!", "SeaWorldHomeStage", "obj2079"},
    {"ScenarioName_obj2645", "Seaside Kingdom Timer Challenge 2", "SeaWorldHomeStage", "obj2645"},
    {"ScenarioName_obj1622", "Shopping in Bubblaine", "SeaWorldHomeStage", "obj1622"},
    {"ScenarioName_obj1277", "The Glass Is Half Full!", "SeaWorldHomeStage", "obj1277"},
    {"ScenarioName_obj2097", "Underwater Highway Tunnel", "SeaWorldHomeStage", "obj2097"},
    {"ScenarioName_obj2558", "Peach in the Seaside Kingdom", "SeaWorldHomeStage", "obj2558"},
    {"ScenarioName_obj2248", "Bonjour, Dorrie!", "SeaWorldHomeStage", "obj2248"},
    {"ScenarioName_obj1955", "Secret Path to Bubblaine!", "SeaWorldHomeStage", "obj1955"},
    {"ScenarioName_obj3052", "Found with Seaside Kingdom Art", "SeaWorldHomeStage", "obj3052"},
    {"ScenarioName_obj3622", "Bubblaine Northern Reaches", "SeaWorldHomeStage", "obj3622"},
    {"ScenarioName_obj382", "The Stone Pillar Seal", "SeaWorldHomeStage", "obj382"},
    {"ScenarioName_obj1863", "Good Job, Captain Toad!", "SeaWorldHomeStage", "obj1863"},
    {"ScenarioName_obj2578", "Underwater Highway East: Explore!", "SeaWorldHomeStage", "obj2578"},
    {"ScenarioName_obj2268", "Merci, Dorrie!", "SeaWorldHomeStage", "obj2268"},
    {"ScenarioName_obj1973", "Sea Gardening: Canyon Seed", "SeaWorldHomeStage", "obj1973"},
    {"ScenarioName_obj1558", "On the Cliff Overlooking the Beach", "SeaWorldHomeStage", "obj1558"},
    {"ScenarioName_obj2689", "A Fine Detail on the Glass", "SeaWorldHomeStage", "obj2689"},
    {"ScenarioName_obj1665", "Underwater Highway West: Explore!", "SeaWorldHomeStage", "obj1665"},
    {"ScenarioName_obj2394", "Under a Dangerous Ceiling", "SeaWorldHomeStage", "obj2394"},
    {"ScenarioName_obj1831", "Sea Gardening: Inlet Seed", "SeaWorldHomeStage", "obj1831"},
    {"ScenarioName_obj2652", "Seaside Kingdom Timer Challenge 3", "SeaWorldHomeStage", "obj2652"},
    {"ScenarioName_obj2802", "Seaside Kingdom Regular Cup", "SeaWorldHomeStage", "obj2802"},
    {"ScenarioName_obj2803", "Seaside Kingdom Master Cup", "SeaWorldHomeStage", "obj2803"},
    {"ScenarioName_obj39", "A Strong Simmer", "LavaWorldCostumeStage", "obj39"},
    {"ScenarioName_obj20", "An Extreme Simmer", "LavaWorldCostumeStage", "obj20"},
    {"ScenarioName_obj357", "Beach Volleyball: Champ", "SeaWorldBeachVolleyBallZone", "obj357"},
    {"ScenarioName_obj385", "Beach Volleyball: Hero of the Beach!", "SeaWorldBeachVolleyBallZone", "obj385"},
    {"ScenarioName_obj18", "Seaside Kingdom Timer Challenge 1", "SeaWorld2DSmallZone", "obj18"},
    {"ScenarioName_obj42", "Secret of the Mural", "SandWorldKillerTowerZone", "obj42"},
    {"ScenarioName_obj210", "Taking Notes: In the Wall Painting", "SandWorldKillerTowerZone", "obj210"},
    {"ScenarioName_obj24", "Shopping in Shiveria", "SnowWorldShopStage", "obj24"},
    {"ScenarioName_obj27", "Metro Kingdom Timer Challenge 1", "CityWorldTimerAthletic003Zone", "obj27"},
    {"ScenarioName_obj3772", "The Nut in the Red Maze", "ForestWorldHomeStage", "obj3772"},
    {"ScenarioName_obj5180", "Hey Out There, Captain Toad!", "ForestWorldHomeStage", "obj5180"},
    {"ScenarioName_obj7360", "Inside a Rock in the Forest", "ForestWorldHomeStage", "obj7360"},
    {"ScenarioName_obj5183", "The Nut in the Robot Storeroom", "ForestWorldHomeStage", "obj5183"},
    {"ScenarioName_obj6962", "Lost in the Tall Trees", "ForestWorldHomeStage", "obj6962"},
    {"ScenarioName_obj5184", "Above the Iron Mountain Path", "ForestWorldHomeStage", "obj5184"},
    {"ScenarioName_obj5185", "Taking Notes: On Top of the Wall", "ForestWorldHomeStage", "obj5185"},
    {"ScenarioName_obj6343", "Peach in the Wooded Kingdom", "ForestWorldHomeStage", "obj6343"},
    {"ScenarioName_obj7205", "I Met an Uproot!", "ForestWorldHomeStage", "obj7205"},
    {"ScenarioName_obj6968", "Wooded Kingdom Master Cup", "ForestWorldHomeStage", "obj6968"},
    {"ScenarioName_obj4127", "The Nut at the Dead End", "ForestWorldHomeStage", "obj4127"},
    {"ScenarioName_obj3577", "Atop the Tall Tree", "ForestWorldHomeStage", "obj3577"},
    {"ScenarioName_obj6560", "Bird Traveling the Forest", "ForestWorldHomeStage", "obj6560"},
    {"ScenarioName_obj3942", "Love in the Forest Ruins", "ForestWorldHomeStage", "obj3942"},
    {"ScenarioName_obj5574", "Fire in the Cave", "ForestWorldHomeStage", "obj5574"},
    {"ScenarioName_obj6164", "Caught Hopping in the Forest!", "ForestWorldHomeStage", "obj6164"},
    {"ScenarioName_obj5887", "The Nut Under the Observation Deck", "ForestWorldHomeStage", "obj5887"},
    {"ScenarioName_obj4052", "Thanks for the Charge!", "ForestWorldHomeStage", "obj4052"},
    {"ScenarioName_obj5309", "Taking Notes: Stretching", "ForestWorldHomeStage", "obj5309"},
    {"ScenarioName_obj6110", "High Up on a Rock Wall", "ForestWorldHomeStage", "obj6110"},
    {"ScenarioName_obj7299", "Wooded Kingdom Timer Challenge 3", "ForestWorldHomeStage", "obj7299"},
    {"ScenarioName_obj1840", "High Up in the Cave", "ForestWorldHomeStage", "obj1840"},
    {"ScenarioName_obj6078", "Secret Path to the Steam Gardens!", "ForestWorldHomeStage", "obj6078"},
    {"ScenarioName_obj7463", "Found with Wooded Kingdom Art", "ForestWorldHomeStage", "obj7463"},
    {"ScenarioName_obj5190", "Hot, Hot, Hot from the Campfire", "ForestWorldHomeStage", "obj5190"},
    {"ScenarioName_obj5652", "The Nut that Grew on the Tall Fence", "ForestWorldHomeStage", "obj5652"},
    {"ScenarioName_obj6241", "Wooded Kingdom Regular Cup", "ForestWorldHomeStage", "obj6241"},
    {"ScenarioName_obj6970", "Jammin' in the Wooded Kingdom", "ForestWorldHomeStage", "obj6970"},
    {"ScenarioName_obj424", "Flower Thieves of Sky Garden", "ForestWorldHomeStage", "obj424"},
    {"ScenarioName_obj2309", "Behind the Rock Wall", "ForestWorldHomeStage", "obj2309"},
    {"ScenarioName_obj5142", "Shopping in Steam Gardens", "ForestWorldHomeStage", "obj5142"},
    {"ScenarioName_obj493", "Looking Down on the Goombas", "ForestWorldHomeStage", "obj493"},
    {"ScenarioName_obj3694", "Climb the Cliff to Get the Nut", "ForestWorldHomeStage", "obj3694"},
    {"ScenarioName_obj4352", "Tucked Away Inside the Tunnel", "ForestWorldHomeStage", "obj4352"},
    {"ScenarioName_obj1667", "Path to the Secret Flower Field", "ForestWorldHomeStage", "obj1667"},
    {"ScenarioName_obj7285", "Swing Around Secret Flower Field", "ForestWorldHomeStage", "obj7285"},
    {"ScenarioName_obj4503", "Cracked Nut on a Crumbling Tower", "ForestWorldHomeStage", "obj4503"},
    {"ScenarioName_obj4508", "The Nut 'Round the Corner", "ForestWorldHomeStage", "obj4508"},
    {"ScenarioName_obj6371", "Wooded Kingdom Timer Challenge 1", "ForestWorldHomeStage", "obj6371"},
    {"ScenarioName_obj4570", "Over the Cliff's Edge", "ForestWorldHomeStage", "obj4570"},
    {"ScenarioName_obj5621", "Moon Shards in the Forest", "ForestWorldHomeStage", "obj5621"},
    {"ScenarioName_obj5161", "Invader in the Sky Garden", "ForestWorldHomeStage", "obj5161"},
    {"ScenarioName_obj1064", "Road to Sky Garden", "ForestWorldHomeStage", "obj1064"},
    {"ScenarioName_obj6177", "Rolling Rock in the Woods", "ForestWorldHomeStage", "obj6177"},
    {"ScenarioName_obj52", "Flooding Pipeway", "ForestWorldWaterExStage", "obj52"},
    {"ScenarioName_obj138", "Flooding Pipeway Ceiling Secret", "ForestWorldWaterExStage", "obj138"},
    {"ScenarioName_obj399", "Metro Kingdom Timer Challenge 2", "CityWorldTimerAthletic002Zone", "obj399"},
    {"ScenarioName_obj489", "City Hall Lost & Found", "CityWorldMainTowerStage", "obj489"},
    {"ScenarioName_obj8", "Deep Woods Treasure Trap", "ForestWorldWoodsTreasureStage", "obj8"},
    {"ScenarioName_obj38", "Moon Shards in the Sea", "SeaWorldBottomHollowZone", "obj38"},
    {"ScenarioName_obj20", "Strange Neighborhood", "SandWorldRotateExStage", "obj20"},
    {"ScenarioName_obj206", "Above a Strange Neighborhood", "SandWorldRotateExStage", "obj206"},
    {"ScenarioName_obj32", "Along the Cliff Face", "MoonWorldHome2DZone", "obj32"},
    {"ScenarioName_obj139", "Taking Notes: In Low Gravity", "MoonWorldHome2DZone", "obj139"},
    {"ScenarioName_obj276", "Atop a Blustery Arch", "SnowWorldByugoZone", "obj276"},
    {"ScenarioName_obj272", "Icy Jump Challenge", "SnowWorldByugoZone", "obj272"},
    {"ScenarioName_obj478", "Motor Scooter Daredevil!", "BikeSteelExStage", "obj478"},
    {"ScenarioName_obj666", "Full-Throttle Scooting!", "BikeSteelExStage", "obj666"},
    {"ScenarioName_obj335", "Caught on a Big Horn", "BossRaidWorldHomeStage", "obj335"},
    {"ScenarioName_obj405", "Rolling Rock on the Battlefield", "BossRaidWorldHomeStage", "obj405"},
    {"ScenarioName_obj30", "Battle with the Lord of Lightning!", "BossRaidWorldHomeStage", "obj30"},
    {"ScenarioName_obj256", "In the Ancient Treasure Chest", "BossRaidWorldHomeStage", "obj256"},
    {"ScenarioName_obj353", "Upon the Broken Arch", "BossRaidWorldHomeStage", "obj353"},
    {"ScenarioName_obj143", "Peach in the Ruined Kingdom", "BossRaidWorldHomeStage", "obj143"},
    {"ScenarioName_obj559", "Taking Notes: Ocean-Bottom Maze", "SeaWorld2DLargeZone", "obj559"},
    {"ScenarioName_obj365", "Ocean-Bottom Maze: Hidden Room", "SeaWorld2DLargeZone", "obj365"},
    {"ScenarioName_obj13", "Ocean-Bottom Maze: Treasure", "SeaWorld2DLargeZone", "obj13"},
    {"ScenarioName_obj9", "Employees Only", "SandWorldShopStage", "obj9"},
    {"ScenarioName_obj21", "Shopping in Tostarena", "SandWorldShopStage", "obj21"},
    {"ScenarioName_obj705", "Scaling Pitchblack Mountain", "DonsukeExStage", "obj705"},
    {"ScenarioName_obj1075", "Reaching Pitchblack Island", "DonsukeExStage", "obj1075"},
    {"ScenarioName_obj1477", "Bullet Billding", "PoleKillerExStage", "obj1477"},
    {"ScenarioName_obj1583", "One Man's Trash...", "PoleKillerExStage", "obj1583"},
    {"ScenarioName_obj95", "Bowser's Castle Treasure Vault", "SkyWorldTreasureStage", "obj95"},
    {"ScenarioName_obj4", "Fruit Feast Under Siege", "ShootingCityYoshiExStage", "obj4"},
    {"ScenarioName_obj3", "Yoshi Under Siege", "ShootingCityYoshiExStage", "obj3"},
    {"ScenarioName_obj650", "Center of the Galaxy", "Galaxy2DExStage", "obj650"},
    {"ScenarioName_obj864", "Edge of the Galaxy", "Galaxy2DExStage", "obj864"},
    {"ScenarioName_obj87", "Ice Cave Treasure", "SandWorldPressExStage", "obj87"},
    {"ScenarioName_obj280", "RC Car Pro!", "RadioControlExStage", "obj280"},
    {"ScenarioName_obj337", "RC Car Champ!", "RadioControlExStage", "obj337"},
    {"ScenarioName_obj232", "Colossal Ruins: Dash! Jump!", "RocketFlowerExStage", "obj232"},
    {"ScenarioName_obj302", "Sinking Colossal Ruins: Hurry!", "RocketFlowerExStage", "obj302"},
    {"ScenarioName_obj14", "The Treasure Chest in the Veggies", "LavaWorldTreasureStage", "obj14"},
    {"ScenarioName_obj91", "Spinning-Platforms Treasure", "ForestWorldBonusStage", "obj91"},
    {"ScenarioName_obj5", "Skimming the Poison Tide", "PoisonWaveExStage", "obj5"},
    {"ScenarioName_obj381", "Slipping Through the Poison Tide", "PoisonWaveExStage", "obj381"},
    {"ScenarioName_obj681", "Looking Back in the Dark Waterway", "SeaWorldUtsuboCaveStage", "obj681"},
    {"ScenarioName_obj34", "Luncheon Kingdom Slots", "LavaBonus1Zone", "obj34"},
    {"ScenarioName_obj66", "Moon Shards Under Siege", "ShootingCityExStage", "obj66"},
    {"ScenarioName_obj1539", "Sharpshooting Under Siege", "ShootingCityExStage", "obj1539"},
    {"ScenarioName_obj76", "Treasure Trap Hidden in the Inlet", "SeaWorldCoveCaveZone", "obj76"},
    {"ScenarioName_obj690", "Secret 2D Treasure", "DotHardExStage", "obj690"},
    {"ScenarioName_obj723", "2D Boost from Bullet Bill", "DotHardExStage", "obj723"},
    {"ScenarioName_obj216", "Flower Road Reach", "RailCollisionExStage", "obj216"},
    {"ScenarioName_obj171", "Flower Road Run", "RailCollisionExStage", "obj171"},
    {"ScenarioName_obj131", "Found with Mushroom Kingdom Art", "PeachWorldCastleStage", "obj131"},
    {"ScenarioName_obj101", "Loose-Tile Trackdown", "PeachWorldCastleStage", "obj101"},
    {"ScenarioName_obj71", "Light from the Ceiling", "PeachWorldCastleStage", "obj71"},
    {"ScenarioName_obj1667", "Down and Back Breakdown Road", "KillerRoadExStage", "obj1667"},
    {"ScenarioName_obj3539", "Below Breakdown Road", "KillerRoadExStage", "obj3539"},
    {"ScenarioName_obj119", "The Invisible Maze", "SandWorldMeganeExStage", "obj119"},
    {"ScenarioName_obj253", "Skull Sign in the Transparent Maze", "SandWorldMeganeExStage", "obj253"},
    {"ScenarioName_obj92", "Sphynx's Hidden Vault", "MoonWorldSphinxRoom", "obj92"},
    {"ScenarioName_obj269", "A Successful Repair Job", "GotogotonExStage", "obj269"},
    {"ScenarioName_obj9", "The Hole in the Desert", "SandWorldUnderground001Stage", "obj9"},
    {"ScenarioName_obj244", "Binding Band Returned", "SandWorldUnderground001Stage", "obj244"},
    {"ScenarioName_obj321", "Under the Mummy's Curse", "SandWorldUnderground001Stage", "obj321"},
    {"ScenarioName_obj30", "Rumble in Crumbleden: Rematch", "RevengeBossRaidStage", "obj30"},
    {"ScenarioName_obj25", "Fruit Feast on the Sinking Island", "SenobiTowerYoshiExStage", "obj25"},
    {"ScenarioName_obj26", "Yoshi on the Sinking Island", "SenobiTowerYoshiExStage", "obj26"},
    {"ScenarioName_obj13", "The Sphynx's Underwater Vault", "SeaWorldSecretStage", "obj13"},
    {"ScenarioName_obj315", "Jump Onto the Transparent Lift", "MeganeLiftExStage", "obj315"},
    {"ScenarioName_obj217", "Where the Transparent Platforms End", "MeganeLiftExStage", "obj217"},
    {"ScenarioName_obj3706", "Freezing Waterway: Hidden Room", "WaterTubeExStage", "obj3706"},
    {"ScenarioName_obj3240", "Through the Freezing Waterway", "WaterTubeExStage", "obj3240"},
    {"ScenarioName_obj371", "Nice Shot with the Chain Chomp!", "WanwanClashExStage", "obj371"},
    {"ScenarioName_obj504", "Very Nice Shot with the Chain Chomp!", "WanwanClashExStage", "obj504"},
    {"ScenarioName_obj6019", "Hidden Chasm Passage", "Lift2DExStage", "obj6019"},
    {"ScenarioName_obj6784", "Past the Chasm Lifts", "Lift2DExStage", "obj6784"},
    {"ScenarioName_obj218", "Jizo's Big Adventure", "JizoSwitchExStage", "obj218"},
    {"ScenarioName_obj543", "Jizo and the Hidden Room", "JizoSwitchExStage", "obj543"},
    {"ScenarioName_obj1487", "Lake Gardening: Spiky Passage Seed", "LakeWorldTownZone", "obj1487"},
    {"ScenarioName_obj1120", "I Feel Underdressed", "LakeWorldTownZone", "obj1120"},
    {"ScenarioName_obj1329", "Space Is \"In\" Right Now", "LakeWorldTownZone", "obj1329"},
    {"ScenarioName_obj1434", "Rooftop of the Water Plaza", "LakeWorldTownZone", "obj1434"},
    {"ScenarioName_obj371", "Let's Go Swimming, Captain Toad!", "LakeWorldTownZone", "obj371"},
    {"ScenarioName_obj1288", "Deep, Deep Down", "LakeWorldTownZone", "obj1288"},
    {"ScenarioName_obj488", "End of the Hidden Passage", "LakeWorldTownZone", "obj488"},
    {"ScenarioName_obj398", "I Met a Lake Cheep Cheep!", "LakeWorldTownZone", "obj398"},
    {"ScenarioName_obj1057", "From the Broken Pillar", "LakeWorldTownZone", "obj1057"},
    {"ScenarioName_obj1315", "High-Flying Leap", "LakeWorldTownZone", "obj1315"},
    {"ScenarioName_obj568", "Dorrie-Back Rider", "LakeWorldTownZone", "obj568"},
    {"ScenarioName_obj1277", "Lake Kingdom Timer Challenge 1", "LakeWorldTownZone", "obj1277"},
    {"ScenarioName_obj1074", "What's in the Box?", "LakeWorldTownZone", "obj1074"},
    {"ScenarioName_obj622", "Moon Shards in the Lake", "LakeWorldTownZone", "obj622"},
    {"ScenarioName_obj1333", "That Trendy \"Pirate\" Look", "LakeWorldTownZone", "obj1333"},
    {"ScenarioName_obj1334", "That \"Old West\" Style", "LakeWorldTownZone", "obj1334"},
    {"ScenarioName_obj645", "Lake Fishing", "LakeWorldTownZone", "obj645"},
    {"ScenarioName_obj903", "Secret Path to Lake Lamode!", "LakeWorldTownZone", "obj903"},
    {"ScenarioName_obj772", "Our Secret Little Room", "LakeWorldTownZone", "obj772"},
    {"ScenarioName_obj614", "Cheep Cheep Crossing", "LakeWorldTownZone", "obj614"},
    {"ScenarioName_obj692", "Fork Flickin' to the Summit", "ForkExStage", "obj692"},
    {"ScenarioName_obj4746", "Fork Flickin' Detour", "ForkExStage", "obj4746"},
    {"ScenarioName_obj36", "Shopping in New Donk City", "CityWorldShop01Stage", "obj36"},
    {"ScenarioName_obj125", "Volcano Cave Cruisin'", "CapAppearLavaLiftExStage", "obj125"},
    {"ScenarioName_obj241", "Volcano Cave and Mysterious Clouds", "CapAppearLavaLiftExStage", "obj241"},
    {"ScenarioName_obj4125", "Bon Appetit, Captain Toad!", "LavaWorldHomeStage", "obj4125"},
    {"ScenarioName_obj3419", "Golden Turnip Recipe 3", "LavaWorldHomeStage", "obj3419"},
    {"ScenarioName_obj2584", "Piled on the Salt", "LavaWorldHomeStage", "obj2584"},
    {"ScenarioName_obj5978", "Under the Meat Plateau", "LavaWorldHomeStage", "obj5978"},
    {"ScenarioName_obj5666", "A Tourist in the Luncheon Kingdom!", "LavaWorldHomeStage", "obj5666"},
    {"ScenarioName_obj4871", "Hat-and-Seek: Among the Food", "LavaWorldHomeStage", "obj4871"},
    {"ScenarioName_obj4980", "Taking Notes: Swimming in Magma", "LavaWorldHomeStage", "obj4980"},
    {"ScenarioName_obj340", "Lurking in the Pillar's Shadow", "LavaWorldHomeStage", "obj340"},
    {"ScenarioName_obj5778", "Peach in the Luncheon Kingdom", "LavaWorldHomeStage", "obj5778"},
    {"ScenarioName_obj5616", "Is This an Ingredient Too?!", "LavaWorldHomeStage", "obj5616"},
    {"ScenarioName_obj5721", "Caught Hopping at the Volcano!", "LavaWorldHomeStage", "obj5721"},
    {"ScenarioName_obj4879", "On Top of a Tall, Tall Roof", "LavaWorldHomeStage", "obj4879"},
    {"ScenarioName_obj5575", "Island of Salt Floating in the Lava", "LavaWorldHomeStage", "obj5575"},
    {"ScenarioName_obj2184", "Light the Lantern on the Small Island", "LavaWorldHomeStage", "obj2184"},
    {"ScenarioName_obj2499", "Light the Two Flames", "LavaWorldHomeStage", "obj2499"},
    {"ScenarioName_obj4890", "Secret Path to Mount Volbono!", "LavaWorldHomeStage", "obj4890"},
    {"ScenarioName_obj3453", "Alcove Behind the Pillars of Magma", "LavaWorldHomeStage", "obj3453"},
    {"ScenarioName_obj5947", "Love Above the Lava", "LavaWorldHomeStage", "obj5947"},
    {"ScenarioName_obj5326", "Light the Far-Off Lanterns", "LavaWorldHomeStage", "obj5326"},
    {"ScenarioName_obj6022", "Taking Notes: Big Pot Swim", "LavaWorldHomeStage", "obj6022"},
    {"ScenarioName_obj6335", "Jammin' in the Luncheon Kingdom", "LavaWorldHomeStage", "obj6335"},
    {"ScenarioName_obj6442", "Treasure Beneath the Cheese Rocks", "LavaWorldHomeStage", "obj6442"},
    {"ScenarioName_obj5859", "The Rooftop Lantern", "LavaWorldHomeStage", "obj5859"},
    {"ScenarioName_obj3420", "Golden Turnip Recipe 2", "LavaWorldHomeStage", "obj3420"},
    {"ScenarioName_obj4862", "From Inside a Bright Stone", "LavaWorldHomeStage", "obj4862"},
    {"ScenarioName_obj3421", "Golden Turnip Recipe 1", "LavaWorldHomeStage", "obj3421"},
    {"ScenarioName_obj5913", "Luncheon Kingdom Timer Challenge 3", "LavaWorldHomeStage", "obj5913"},
    {"ScenarioName_obj3112", "Cookatiel Showdown!", "LavaWorldHomeStage", "obj3112"},
    {"ScenarioName_obj3424", "Luncheon Kingdom: Regular Cup", "LavaWorldHomeStage", "obj3424"},
    {"ScenarioName_obj4867", "From a Crack in the Hard Ground", "LavaWorldHomeStage", "obj4867"},
    {"ScenarioName_obj1097", "The Broodals Are After Some Cookin'", "LavaWorldHomeStage", "obj1097"},
    {"ScenarioName_obj4868", "By the Cannon Pointed at the Big Pot", "LavaWorldHomeStage", "obj4868"},
    {"ScenarioName_obj2590", "Climb Up the Cascading Magma", "LavaWorldHomeStage", "obj2590"},
    {"ScenarioName_obj2174", "Atop the Jutting Crag", "LavaWorldHomeStage", "obj2174"},
    {"ScenarioName_obj5620", "Overlooking a Bunch of Ingredients", "LavaWorldHomeStage", "obj5620"},
    {"ScenarioName_obj5621", "Atop a Column in a Row", "LavaWorldHomeStage", "obj5621"},
    {"ScenarioName_obj1725", "Big Pot on the Volcano: Dive In!", "LavaWorldHomeStage", "obj1725"},
    {"ScenarioName_obj5624", "Surrounded by Tall Mountains", "LavaWorldHomeStage", "obj5624"},
    {"ScenarioName_obj6527", "Diving from the Big Pot!", "LavaWorldHomeStage", "obj6527"},
    {"ScenarioName_obj355", "Under the Cheese Rocks", "LavaWorldHomeStage", "obj355"},
    {"ScenarioName_obj6595", "Found with Luncheon Kingdom Art", "LavaWorldHomeStage", "obj6595"},
    {"ScenarioName_obj6328", "Mechanic: Repairs Complete!", "LavaWorldHomeStage", "obj6328"},
    {"ScenarioName_obj6329", "Luncheon Kingdom: Master Cup", "LavaWorldHomeStage", "obj6329"},
    {"ScenarioName_obj599", "Sewer Treasure", "CityWorldFactory01Zone", "obj599"},
};

inline constexpr MessageData checkpointList[85] = {
    {"Checkpoint_obj153", "Glass Palace", "SeaWorldUnderGlassZone", "obj153(SeaWorldUnderGlassZone[obj1898])"},
    {"Checkpoint_obj1143", "Goomba Woods", "PeachWorldHomeStage", "obj1143"},
    {"Checkpoint_obj1455", "Yoshi's House", "PeachWorldHomeStage", "obj1455"},
    {"Checkpoint_obj1145", "Mushroom Pond", "PeachWorldHomeStage", "obj1145"},
    {"Checkpoint_obj162", "Peach's Castle Main Entrance", "PeachWorldHomeStage", "obj162"},
    {"Checkpoint_obj345", "Ringing-Bells Plateau", "MoonWorldHomeStage", "obj345"},
    {"Checkpoint_obj127", "Ever-After Hill", "MoonWorldHomeStage", "obj127"},
    {"Checkpoint_obj1006", "Quiet Wall", "MoonWorldHomeStage", "obj1006"},
    {"Checkpoint_obj1348", "Wedding Hall", "MoonWorldHomeStage", "obj1348"},
    {"Checkpoint_obj2899", "Mountainside Platform", "ClashWorldHomeStage", "obj2899"},
    {"Checkpoint_obj543", "Swamp Hill", "ClashWorldHomeStage", "obj543"},
    {"Checkpoint_obj545", "Rocky Mountain Summit", "ClashWorldHomeStage", "obj545"},
    {"Checkpoint_obj1726", "Third Courtyard (Front)", "SkyWorldHomeStage", "obj1726"},
    {"Checkpoint_obj2697", "Island in the Sky", "SkyWorldHomeStage", "obj2697"},
    {"Checkpoint_obj1626", "Third Courtyard (Rear)", "SkyWorldHomeStage", "obj1626"},
    {"Checkpoint_obj2028", "Souvenir Shop", "SkyWorldHomeStage", "obj2028"},
    {"Checkpoint_obj182", "Hot Spring Island", "SeaWorldLavaZone", "obj182(SeaWorldLavaZone[obj1399])"},
    {"Checkpoint_obj545", "Second Courtyard", "SkyWorldWallZone", "obj545(SkyWorldWallZone[obj2161])"},
    {"Checkpoint_obj59", "Above Rolling Canyon", "SeaWorldDamageBallZone", "obj59(SeaWorldDamageBallZone[obj1070])"},
    {"Checkpoint_obj212", "Lighthouse", "SeaWorldLighthouseZone", "obj212(SeaWorldLighthouseZone[obj1402])"},
    {"Checkpoint_obj5012", "Rooftop Garden", "CityWorldHomeStage", "obj5012"},
    {"Checkpoint_obj5016", "New Donk City Hall Rooftop", "CityWorldHomeStage", "obj5016"},
    {"Checkpoint_obj4904", "New Donk City Hall Plaza", "CityWorldHomeStage", "obj4904"},
    {"Checkpoint_obj9017", "Construction Access", "CityWorldHomeStage", "obj9017"},
    {"Checkpoint_obj14061", "Isolated Rooftop", "CityWorldHomeStage", "obj14061"},
    {"Checkpoint_obj9086", "Construction Site", "CityWorldHomeStage", "obj9086"},
    {"Checkpoint_obj3994", "Main Street Entrance", "CityWorldHomeStage", "obj3994"},
    {"Checkpoint_obj3996", "Heliport", "CityWorldHomeStage", "obj3996"},
    {"Checkpoint_obj3998", "Mayor Pauline Commemorative Park", "CityWorldHomeStage", "obj3998"},
    {"Checkpoint_obj4000", "Outdoor Cafe", "CityWorldHomeStage", "obj4000"},
    {"Checkpoint_obj8918", "City Outskirts", "CityWorldHomeStage", "obj8918"},
    {"Checkpoint_obj381", "Top-Hat Tower", "CapWorldHomeStage", "obj381"},
    {"Checkpoint_obj2497", "Central Plaza", "CapWorldHomeStage", "obj2497"},
    {"Checkpoint_obj1440", "Corner of the Freezing Sea", "SnowWorldHomeStage", "obj1440"},
    {"Checkpoint_obj1066", "Above the Ice Well", "SnowWorldHomeStage", "obj1066"},
    {"Checkpoint_obj1387", "Snow Kingdom Clifftop", "SnowWorldHomeStage", "obj1387"},
    {"Checkpoint_obj2832", "Island in the Sky", "WaterfallWorldHomeStage", "obj2832"},
    {"Checkpoint_obj3139", "Top of the Big Stump", "WaterfallWorldHomeStage", "obj3139"},
    {"Checkpoint_obj1724", "Stone Bridge", "WaterfallWorldHomeStage", "obj1724"},
    {"Checkpoint_obj597", "Waterfall Basin", "WaterfallWorldHomeStage", "obj597"},
    {"Checkpoint_obj601", "Fossil Falls Heights", "WaterfallWorldHomeStage", "obj601"},
    {"Checkpoint_obj655", "Tostarena Town", "SandWorldHomeStage", "obj655"},
    {"Checkpoint_obj1511", "Moe-Eye Habitat", "SandWorldHomeStage", "obj1511"},
    {"Checkpoint_obj98", "Tostarena Ruins Sand Pillar", "SandWorldHomeStage", "obj98"},
    {"Checkpoint_obj99", "Tostarena Ruins Entrance", "SandWorldHomeStage", "obj99"},
    {"Checkpoint_obj530", "Jaxi Ruins", "SandWorldHomeStage", "obj530"},
    {"Checkpoint_obj525", "Tostarena Ruins Round Tower", "SandWorldHomeStage", "obj525"},
    {"Checkpoint_obj5575", "Southwestern Floating Island", "SandWorldHomeStage", "obj5575"},
    {"Checkpoint_obj1595", "Tostarena Northwest Reaches", "SandWorldHomeStage", "obj1595"},
    {"Checkpoint_obj1597", "Desert Oasis", "SandWorldHomeStage", "obj1597"},
    {"Checkpoint_obj1888", "Main Courtyard Entrance", "SkyWorldCastleZone", "obj1888(SkyWorldCastleZone[obj2160])"},
    {"Checkpoint_obj1890", "Outer Wall", "SkyWorldCastleZone", "obj1890(SkyWorldCastleZone[obj2160])"},
    {"Checkpoint_obj1891", "Beneath the Keep", "SkyWorldCastleZone", "obj1891(SkyWorldCastleZone[obj2160])"},
    {"Checkpoint_obj6423", "Showdown Arena", "SkyWorldCastleZone", "obj6423(SkyWorldCastleZone[obj2160])"},
    {"Checkpoint_obj2134", "Inner Wall", "SkyWorldCastleZone", "obj2134(SkyWorldCastleZone[obj2160])"},
    {"Checkpoint_obj1392", "Main Courtyard", "SkyWorldCastleZone", "obj1392(SkyWorldCastleZone[obj2160])"},
    {"Checkpoint_obj2264", "Ocean Trench West", "SeaWorldHomeStage", "obj2264"},
    {"Checkpoint_obj2266", "Ocean Trench East", "SeaWorldHomeStage", "obj2266"},
    {"Checkpoint_obj1866", "Rolling Canyon", "SeaWorldHomeStage", "obj1866"},
    {"Checkpoint_obj2621", "Diving Platform", "SeaWorldHomeStage", "obj2621"},
    {"Checkpoint_obj1524", "Beach House", "SeaWorldHomeStage", "obj1524"},
    {"Checkpoint_obj3734", "Sky Garden Tower", "ForestWorldHomeStage", "obj3734"},
    {"Checkpoint_obj1841", "Summit Path", "ForestWorldHomeStage", "obj1841"},
    {"Checkpoint_obj6865", "Iron Cage", "ForestWorldHomeStage", "obj6865"},
    {"Checkpoint_obj3708", "Iron Road: Entrance", "ForestWorldHomeStage", "obj3708"},
    {"Checkpoint_obj447", "Iron Road: Halfway Point", "ForestWorldHomeStage", "obj447"},
    {"Checkpoint_obj2821", "Secret Flower Field Entrance", "ForestWorldHomeStage", "obj2821"},
    {"Checkpoint_obj3835", "Observation Deck", "ForestWorldHomeStage", "obj3835"},
    {"Checkpoint_obj7333", "Iron Mountain Path, Station 8", "ForestWorldHomeStage", "obj7333"},
    {"Checkpoint_obj5216", "Forest Charging Station", "ForestWorldHomeStage", "obj5216"},
    {"Checkpoint_obj583", "Courtyard", "LakeWorldTownZone", "obj583(LakeWorldTownZone[obj324])"},
    {"Checkpoint_obj693", "Water Plaza Entrance", "LakeWorldTownZone", "obj693(LakeWorldTownZone[obj324])"},
    {"Checkpoint_obj220", "Water Plaza Terrace", "LakeWorldTownZone", "obj220(LakeWorldTownZone[obj324])"},
    {"Checkpoint_obj1389", "Water Plaza Display Window", "LakeWorldTownZone", "obj1389(LakeWorldTownZone[obj324])"},
    {"Checkpoint_obj839", "Underwater Entrance", "LakeWorldTownZone", "obj839(LakeWorldTownZone[obj324])"},
    {"Checkpoint_obj1323", "Viewing Balcony", "LakeWorldTownZone", "obj1323(LakeWorldTownZone[obj324])"},
    {"Checkpoint_obj4117", "Top of the Peak Climb", "LavaWorldHomeStage", "obj4117"},
    {"Checkpoint_obj4074", "Path to the Meat Plateau", "LavaWorldHomeStage", "obj4074"},
    {"Checkpoint_obj4619", "Salt-Pile Isle", "LavaWorldHomeStage", "obj4619"},
    {"Checkpoint_obj642", "Peronza Plaza", "LavaWorldHomeStage", "obj642"},
    {"Checkpoint_obj2549", "Volcano Cave Entrance", "LavaWorldHomeStage", "obj2549"},
    {"Checkpoint_obj6042", "Floating Sky Island", "LavaWorldHomeStage", "obj6042"},
    {"Checkpoint_obj4120", "Remote Island in the Lava", "LavaWorldHomeStage", "obj4120"},
    {"Checkpoint_obj1061", "Meat Plateau", "LavaWorldHomeStage", "obj1061"},
    {"Checkpoint_obj2292", "Start of the Peak Climb", "LavaWorldHomeStage", "obj2292"},
};

inline constexpr AchievementMessageData achievementList[61] = {
    {"Shine_HideAndSeekCapMan", "Hat-Seeking Missile"},
    {"Souvenir_Count_2", "Souvenir Sleuth"},
    {"Costume_Clothes_2", "Fashion Icon"},
    {"Souvenir_Count_3", "Souvenir Savant"},
    {"Shine_KuriboGirl", "Gaga for Goombette"},
    {"Shine_TravelingPeach_1", "Touring with Princess Peach"},
    {"Shine_CostumeRoom_1", "Wearing It Well!"},
    {"Shine_TravelingPeach_2", "Globe-Trotting with Princess Peach"},
    {"Shine_CostumeRoom_2", "Wearing It Great!"},
    {"Costume_Cap_1", "Hat Maven"},
    {"Shine_CostumeRoom_3", "Wearing It Perfect!"},
    {"Costume_Cap_2", "Hat Icon"},
    {"Capture_Count_1", "Capturing Novice"},
    {"Capture_Count_2", "Capturing Apprentice"},
    {"Other_MoonStoneAll", "Moon Rock Liberator"},
    {"Other_Coin_1", "Loaded with Coins"},
    {"Shine_Shine2D_1", "Flat Moon Finder"},
    {"Shine_Bird", "Traveling-Bird Herder"},
    {"Capture_Count_3", "Capturing Master"},
    {"Other_Coin_2", "Rolling in Coins"},
    {"Shine_Shine2D_2", "Flat Moon Fanatic"},
    {"Other_Coin_3", "Swimming in Coins"},
    {"MiniGame_RaceMan_1", "Koopa Freerunning MVP"},
    {"MiniGame_RaceMan_2", "Koopa Freerunning Hall of Famer"},
    {"Other_Jump", "Jump! Jump! Jump!"},
    {"Other_WorldWarpHoleAll", "World Warper"},
    {"Shine_TreasureBox_1", "Treasure Chest Hunter"},
    {"Shine_TreasureBox_2", "Super Treasure Chest Hunter"},
    {"Shine_HintPhoto_1", "Art Enthusiast"},
    {"Shine_HintPhoto_2", "Art Investigator"},
    {"Shine_CollectAnimalAll", "Master Sheep Herder"},
    {"Shine_Rabbit_1", "Running with Rabbits"},
    {"Shine_Rabbit_2", "Racing with Rabbits"},
    {"Scenario_Ending", "Rescue Princess Peach"},
    {"Shine_CaptainKinopio_1", "Captain Toad Meeter"},
    {"Shine_CollectCoinShop", "Regional Coin Shopper"},
    {"Shine_CaptainKinopio_2", "Captain Toad Greeter"},
    {"Other_CapThrow", "Fly, Cappy, Fly!"},
    {"Shine_TimerAthretic_1", "Timer Challenge Amateur"},
    {"Shine_TimerAthretic_2", "Timer Challenge Professional"},
    {"Shine_MusicNote_1", "Note-Collecting World Tour"},
    {"Shine_CollectBgm", "Music Maestro"},
    {"Shine_MusicNote_2", "Note-Collecting Space Tour"},
    {"Shine_Jugem", "Lakitu Fishing Trip"},
    {"Shine_CapHanger_1", "Rad Hatter"},
    {"Other_CheckPoint_1", "Checkpoint Flagger"},
    {"Shine_CapHanger_2", "Super Rad Hatter"},
    {"Other_CheckPoint_2", "Checkpoint Flag Enthusiast"},
    {"Shine_Seed_1", "Flower-Growing Guru"},
    {"Shine_Seed_2", "Flower-Growing Sage"},
    {"Shine_DigPoint_1", "Ground Pound Instructor"},
    {"Shine_Gather_1", "Power Moon Knight"},
    {"Shine_DigPoint_2", "Ground Pound Professor"},
    {"Shine_Gather_2", "Power Moon Wizard"},
    {"Shine_Gather_3", "Power Moon Ruler"},
    {"Shine_CapThrottle", "Slots Machine"},
    {"MiniGame_FigureWalker", "Supernaturally Sure-Footed"},
    {"Scenario_WorldAll", "Achieve World Peace"},
    {"MiniGame_SphinxQuiz", "Quizmaster"},
    {"Souvenir_Count_1", "Souvenir Sampler"},
    {"Costume_Clothes_1", "Fashion Maven"},
};
}  // namespace MessageMasterList
